import 'dart:ui';

class GameConstants {
  GameConstants._();

  // ── Physics ──
  static const double baseMagnetForce = 2600.0;
  static const double maxHorizontalSpeed = 920.0;
  static const double playerRadius = 10.0;

  // ── Obstacle generation ──
  static const double obstacleMinThickness = 14.0;
  static const double obstacleMaxThickness = 22.0;
  static const double obstacleSpacing = 200.0;
  static const double obstacleSpacingJitter = 0.20; // ±20% random variance
  static const double baseScrollSpeed = 220.0;

  // Per-phase obstacle spacing multiplier (lower = denser = harder)
  static const List<double> phaseSpacingMultipliers = [
    1.15, // Phase 1: comfortable warmup
    1.00, // Phase 2: real game pace
    0.86, // Phase 3: tight rhythm
    0.74, // Phase 4: relentless
    0.64, // Phase 5: god-tier density
  ];

  // Per-phase max consecutive same-side obstacles (enforced in game_engine)
  // Phase 1-2: 2, Phase 3-4: 3, Phase 5: 4

  // ── Safe spawn delay (seconds before first obstacle) ──
  static const double safeSpawnDelay = 0.8;

  // ── 5 Visual & Difficulty Phases ──
  // Phase 1: 0-40    Pure White on Pitch Black (warmup)
  // Phase 2: 41-120  Electric Blue (real game starts)
  // Phase 3: 121-250 Warning Yellow (tighter, faster snaps)
  // Phase 4: 251-420 Crimson Red (brutal, narrow gaps)
  // Phase 5: 421+    Inverted (white bg / black geo), max everything
  static const List<int> phaseThresholds = [0, 50, 130, 260, 430];

  static const List<Color> phaseColors = [
    Color(0xFFFFFFFF), // Phase 1: Pure White
    Color(0xFF007AFF), // Phase 2: Electric Blue
    Color(0xFFFFD60A), // Phase 3: Warning Yellow
    Color(0xFFFF3B30), // Phase 4: Crimson Red
    Color(0xFF000000), // Phase 5: Black (inverted theme)
  ];

  // Speed multipliers per phase (scroll speed × this)
  static const List<double> phaseSpeedMultipliers = [
    1.0, 1.18, 1.40, 1.65, 1.92,
  ];

  // Magnet multipliers (lateral pull × this)
  static const List<double> phaseMagnetMultipliers = [
    0.55, 0.72, 0.92, 1.15, 1.40,
  ];

  // Gap shrink factors per phase (1.0 = widest, lower = narrower gaps)
  static const List<double> phaseGapFactors = [
    1.0, 0.88, 0.74, 0.62, 0.52,
  ];

  // ── Shield ──
  // First shield at 20, second at 60, then x2 each time
  static const int firstShieldScore = 20;
  static const int secondShieldScore = 60;
  static const double shieldInvincibilityDuration = 3.0;

  // ── Ads (Time-only Lock) ──
  static const int interstitialMinIntervalSeconds = 70;
  static const double iapPrice = 2.99;
  static const String iapProductId = 'remove_ads';

  // AdMob IDs can be overridden with --dart-define for production.
  static const String androidAppId = String.fromEnvironment(
    'ANDROID_ADMOB_APP_ID',
    defaultValue: 'ca-app-pub-4151123662328725~3767987674',
  );
  static const String iosAppId = String.fromEnvironment(
    'IOS_ADMOB_APP_ID',
    defaultValue: 'ca-app-pub-3940256099942544~1458002511', // TODO: replace with iOS production ID
  );

  static const String androidBannerId = String.fromEnvironment(
    'ANDROID_BANNER_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-3940256099942544/6300978111',
  );
  static const String iosBannerId = String.fromEnvironment(
    'IOS_BANNER_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-3940256099942544/2934735716',
  );
  static const String androidInterstitialId = String.fromEnvironment(
    'ANDROID_INTERSTITIAL_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-4151123662328725/3311844641',
  );
  static const String iosInterstitialId = String.fromEnvironment(
    'IOS_INTERSTITIAL_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-3940256099942544/4411468910',
  );
  static const String androidRewardedId = String.fromEnvironment(
    'ANDROID_REWARDED_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-4151123662328725/6877578771',
  );
  static const String iosRewardedId = String.fromEnvironment(
    'IOS_REWARDED_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-3940256099942544/1712485313',
  );

  // Leaderboard IDs. Override with --dart-define.
  static const String androidLeaderboardId = String.fromEnvironment(
    'ANDROID_LEADERBOARD_ID',
    defaultValue: 'CgkI8OfvjJcWEAIQAQ',
  );
  static const String iosLeaderboardId = String.fromEnvironment(
    'IOS_LEADERBOARD_ID',
    defaultValue: 'polarity_leaderboard',
  );

  // ── Revive ──
  static const double reviveInvincibilityDuration = 3.0;
  static const int reviveCountdownSeconds = 3;

  // ── Tutorial ──
  static const int tutorialFadeScore = 5;

  // ── Review ──
  static const int minScoreForReview = 20;

  // ── Privacy ──
  static const String privacyPolicyUrl = 'https://polarityprivacy.netlify.app/';

  // ── death roasts (300) ──
  static const List<String> deathRoasts = [
    "the audacity to press restart right now 😂😂😂😂😂😂",
    "u have NO RIGHT pressing restart after that 😭😭😭😭😭😭",
    "pls tell me u r not about to press restart again 😂😂😂😂😂😂",
    "u really think the next run is gonna be different 😭😭😭😭😭😭",
    "hitting restart isnt gonna magically give u skill 😂😂😂😂😂😂",
    "just leave it on the fail screen its safer there 😭😭😭😭😭😭",
    "why r u still trying u literally proved u cant do this 😂😂😂😂😂😂",
    "the restart button is exhausted pls leave it alone 😭😭😭😭😭😭",
    "do u just enjoy watching urself fail 😭😭😭😭😭😭",
    "imagine failing like that and then confidently pressing play again 😂😂😂😂😂😂",
    "take a hint and close the app already 😂😂😂😂😂😂",
    "the definition of delusion is whatever u r doing right now 😭😭😭😭😭😭",
    "u really sat there, lost, and said 'yeah let me do it again' 😂😂😂😂😂😂",
    "the restart button is begging for mercy right now 😭😭😭😭😭😭",
    "u press restart like u actually have a plan this time 😂😂😂😂😂😂",
    "stop touching the screen u are only making it worse 😭😭😭😭😭😭",
    "another restart another immediate disappointment 😂😂😂😂😂😂",
    "u can restart 1000 times and it still wont fix ur gameplay 😭😭😭😭😭😭",
    "just put the phone down and walk away. seriously. 😭😭😭😭😭😭",
    "are u trying to set a record for most restarts in a minute 😂😂😂😂😂😂",
    "u are actively draining my battery for absolutely nothing 😂😂😂😂😂😂",
    "please don't tell anyone you play this game 😂😂😂😂😂😂",
    "every second u play this is a second u could have spent improving ur score 😂😂😂😂😂😂",
    "why are u spending ur free time doing something u are this bad at 😂😂😂😂😂😂",
    "u are burning through screen time for zero results 😂😂😂😂😂😂",
    "u could have learned a new language by now but instead u are here 😭😭😭😭😭😭",
    "there are so many better ways to waste time than this 😂😂😂😂😂😂",
    "the sheer amount of time wasted on that run is painful 😭😭😭😭😭😭",
    "u are dragging this out and making it painful for everyone 😂😂😂😂😂😂",
    "literally go outside and look at the sky immediately 😭😭😭😭😭😭",
    "ur wasting electricity just sitting there failing 😂😂😂😂😂😂",
    "i want those two minutes of my life back 😭😭😭😭😭😭",
    "u are literally throwing ur time away on a screen 😂😂😂😂😂😂",
    "do u not have anything better to do with ur time 😭😭😭😭😭😭",
    "u could be doing literally anything else right now 😂😂😂😂😂😂",
    "the absolute definition of a waste of time 😭😭😭😭😭😭",
    "u are achieving absolutely nothing right now 😂😂😂😂😂😂",
    "is this really how u want to spend ur day 😭😭😭😭😭😭",
    "u are actively wasting ur own potential just to fail here 😂😂😂😂😂😂",
    "the hours u spent on this and u still look like a beginner 😭😭😭😭😭😭",
    "for the love of everything please just uninstall this right now 😂😂😂😂😂😂",
    "do us all a favor and delete the app immediately 😭😭😭😭😭😭",
    "i am on my knees begging u to remove this from ur phone 😂😂😂😂😂😂",
    "there is an uninstall button in the settings please use it 😭😭😭😭😭😭",
    "if u have any gaming dignity left u will delete this 😂😂😂😂😂😂",
    "the app store is currently accepting returns on ur download 😭😭😭😭😭😭",
    "u are holding me back please uninstall so i can be free 😂😂😂😂😂😂",
    "i will personally pay u to never open this app again 😭😭😭😭😭😭",
    "just long press the icon and hit remove it is that simple 😂😂😂😂😂😂",
    "i am formally requesting u to uninstall me 😭😭😭😭😭😭",
    "save urself the humiliation and just delete it now 😂😂😂😂😂😂",
    "u don't need this kind of negativity in ur phone just uninstall 😭😭😭😭😭😭",
    "the best move u can make right now is dragging this app to the recycle bin 😂😂😂😂😂😂",
    "i am begging the operating system to forcefully uninstall me 😭😭😭😭😭😭",
    "u are not built for this delete it and move on 😂😂😂😂😂😂",
    "uninstalling is the only way u can win at this point 😭😭😭😭😭😭",
    "if u delete the app now u can pretend this never happened 😂😂😂😂😂😂",
    "im putting up an eviction notice on ur home screen 😭😭😭😭😭😭",
    "u are a liability to this app please remove it immediately 😂😂😂😂😂😂",
    "u clearly downloaded the wrong game just let it go 😭😭😭😭😭😭",
    "u are completely and utterly washed 😂😂😂😂😂😂",
    "it is over for u. pack it up. go home. 😭😭😭😭😭😭",
    "u are officially finished in every sense of the word 😂😂😂😂😂😂",
    "there is no coming back from a failure of that magnitude 😭😭😭😭😭😭",
    "ur high score is absolutely cooked beyond saving 😂😂😂😂😂😂",
    "u are done. completely done. 😭😭😭😭😭😭",
    "the absolute state of ur run right now is beyond repair 😂😂😂😂😂😂",
    "u are entirely washed up as a player 😭😭😭😭😭😭",
    "that run was the final nail in the scoreboard 😂😂😂😂😂😂",
    "u have officially hit rock bottom and started digging 😭😭😭😭😭😭",
    "there is zero hope left for ur run 😂😂😂😂😂😂",
    "u are absolutely toast. completely finished. 😭😭😭😭😭😭",
    "the game is officially declaring u a lost cause 😂😂😂😂😂😂",
    "u have been permanently revoked from the winner's circle 😭😭😭😭😭😭",
    "u are so finished they are archiving ur score right now 😂😂😂😂😂😂",
    "ur potential has completely vanished 😭😭😭😭😭😭",
    "the curtains have closed and u are being booed off stage 😂😂😂😂😂😂",
    "u are officially categorized as a hopeless case 😭😭😭😭😭😭",
    "there is nothing left for u here just leave 😂😂😂😂😂😂",
    "u are comprehensively and irreparably defeated 😭😭😭😭😭😭",
    "i am physically cringing at how bad that was 😂😂😂😂😂😂",
    "im hiding the screen because im embarrassed for u 😭😭😭😭😭😭",
    "i would deny knowing u if anyone asked about that run 😂😂😂😂😂😂",
    "u should be legally required to apologize for that gameplay 😭😭😭😭😭😭",
    "im feeling second hand embarrassment through the screen 😂😂😂😂😂😂",
    "if i played like that i would simply never speak again 😭😭😭😭😭😭",
    "u are bringing shame to the entire leaderboard with that run 😂😂😂😂😂😂",
    "i have never felt so mortified on behalf of someone else 😭😭😭😭😭😭",
    "the sheer amount of cringe i just experienced is off the charts 😂😂😂😂😂😂",
    "u should honestly wear a paper bag over ur head after that 😭😭😭😭😭😭",
    "i am red in the face just from watching u fail 😂😂😂😂😂😂",
    "please tell me nobody else saw u do that 😭😭😭😭😭😭",
    "i would delete my digital footprint if i played like that 😂😂😂😂😂😂",
    "the humiliation must be absolutely crushing u right now 😭😭😭😭😭😭",
    "u are an absolute embarrassment to the gaming community 😂😂😂😂😂😂",
    "i literally have to look away because it hurts to watch 😭😭😭😭😭😭",
    "u should be blushing right now because that was dreadful 😂😂😂😂😂😂",
    "the secondhand shame is so strong i need a moment 😭😭😭😭😭😭",
    "i am actively embarrassed to be running on ur device 😂😂😂😂😂😂",
    "u just posted a certified cringe moment straight to the database 😭😭😭😭😭😭",
    "the absolute sheer confidence u had right before failing is sending me 😂😂😂😂😂😂",
    "u really thought u ate that up didn't u 😭😭😭😭😭😭",
    "u played that like u knew what u were doing and still failed 😂😂😂😂😂😂",
    "the delusion u must have to think u are actually good at this 😭😭😭😭😭😭",
    "u are so confidently terrible it is actually inspiring 😂😂😂😂😂😂",
    "i love how u just march towards failure with absolute certainty 😭😭😭😭😭😭",
    "u really believed u were about to set a new high score didn't u 😂😂😂😂😂😂",
    "the false hope u give urself before every run is tragic 😭😭😭😭😭😭",
    "u play with the swagger of someone who isn't consistently losing 😂😂😂😂😂😂",
    "u actually thought u could make that gap. that is wild. 😭😭😭😭😭😭",
    "ur confidence is completely unmatched by ur actual skill level 😂😂😂😂😂😂",
    "u walk into the walls with so much purpose i almost respect it 😭😭😭😭😭😭",
    "u really hyped urself up just to fail immediately 😂😂😂😂😂😂",
    "the absolute nerve to play that badly and not be embarrassed 😭😭😭😭😭😭",
    "u are living in a fantasy world if u think u can win 😂😂😂😂😂😂",
    "the unwavering belief u have in ur own failure is beautiful 😭😭😭😭😭😭",
    "u actually thought u were gonna pull that off 😂😂😂😂😂😂",
    "ur optimism is the funniest part of this whole experience 😭😭😭😭😭😭",
    "u approach every obstacle like u didn't just fail to the exact same one 😂😂😂😂😂😂",
    "the pure unadulterated delusion is carrying u right now 😭😭😭😭😭😭",
    "aww u tried so hard and still failed miserably 😂😂😂😂😂😂",
    "its okay not everyone is meant to be good at things 😭😭😭😭😭😭",
    "bless ur heart u really thought u had it 😂😂😂😂😂😂",
    "im sure u will get it next time. definitely. 😭😭😭😭😭😭",
    "participation trophies were invented for players exactly like u 😂😂😂😂😂😂",
    "at least u are consistently terrible so u have that going for u 😭😭😭😭😭😭",
    "don't worry nobody expects u to actually win anyway 😂😂😂😂😂😂",
    "u are doing great sweetie just keep failing 😭😭😭😭😭😭",
    "its okay to be the worst player in the world someone has to be 😂😂😂😂😂😂",
    "im so proud of u for managing to press the play button 😭😭😭😭😭😭",
    "aww look at u trying to navigate a basic obstacle 😂😂😂😂😂😂",
    "im sure ur very good at other things just not this 😭😭😭😭😭😭",
    "u gave it ur absolute best and it was still awful 😂😂😂😂😂😂",
    "don't cry u can always pretend u meant to do that 😭😭😭😭😭😭",
    "ur trying so hard and getting absolutely nowhere its adorable 😂😂😂😂😂😂",
    "i admire ur persistence even though its completely pointless 😭😭😭😭😭😭",
    "u really gave that wall a good hug didn't u 😂😂😂😂😂😂",
    "its fine we all have our weaknesses yours just happens to be this game 😭😭😭😭😭😭",
    "im sure the wall appreciated u running straight into it 😂😂😂😂😂😂",
    "u are so brave for continuing to play after being humiliated 😭😭😭😭😭😭",
    "i give up. i physically give up watching u play. 😂😂😂😂😂😂",
    "just surrender u are entirely outmatched 😭😭😭😭😭😭",
    "throw the towel in before u embarrass urself further 😂😂😂😂😂😂",
    "i am officially resigning as ur game host 😭😭😭😭😭😭",
    "just put the phone down and accept ur defeat 😂😂😂😂😂😂",
    "there is no shame in admitting u are terrible just give up 😭😭😭😭😭😭",
    "i am tapping out i cannot handle watching this anymore 😂😂😂😂😂😂",
    "u need to surrender immediately for ur own good 😭😭😭😭😭😭",
    "i am waving the white flag on ur behalf 😂😂😂😂😂😂",
    "just accept that u are never going to beat this and move on 😭😭😭😭😭😭",
    "u have lost all privileges to continue playing just quit 😂😂😂😂😂😂",
    "giving up is the only logical choice u have left 😭😭😭😭😭😭",
    "i am ending this run immediately u are done 😂😂😂😂😂😂",
    "u need to lay down ur arms and accept ur fate 😭😭😭😭😭😭",
    "just walk away there is nothing left for u to accomplish here 😂😂😂😂😂😂",
    "i am officially revoking ur right to play just give up 😭😭😭😭😭😭",
    "surrendering is a sign of wisdom when u are this bad 😂😂😂😂😂😂",
    "just forfeit the match u are completely out of ur depth 😭😭😭😭😭😭",
    "i am begging u to just throw ur hands up and quit 😂😂😂😂😂😂",
    "accept ur absolute failure and never open this app again 😭😭😭😭😭😭",
    "i genuinely cannot comprehend how u failed there 😂😂😂😂😂😂",
    "that was so bad it felt intentional 😭😭😭😭😭😭",
    "i refuse to believe a human being made those decisions 😂😂😂😂😂😂",
    "there is no way u actually thought that was gonna work 😭😭😭😭😭😭",
    "how is it even physically possible to fail that badly 😂😂😂😂😂😂",
    "im staring at the screen in absolute shock 😭😭😭😭😭😭",
    "that was genuinely the worst thing i have ever witnessed 😂😂😂😂😂😂",
    "i am at a total loss for words right now 😭😭😭😭😭😭",
    "i didn't think it was possible to play this poorly 😂😂😂😂😂😂",
    "that wasn't a mistake that was a gameplay choice 😭😭😭😭😭😭",
    "u somehow keep finding new ways to disappoint me 😂😂😂😂😂😂",
    "i am completely baffled by ur decision making 😭😭😭😭😭😭",
    "did u honestly believe u were going to survive that 😂😂😂😂😂😂",
    "u have defied all logic and reason by failing there 😭😭😭😭😭😭",
    "i am legitimately stunned at the sheer magnitude of that failure 😂😂😂😂😂😂",
    "u just rewrote the definition of a disaster 😭😭😭😭😭😭",
    "i have seen a lot of bad players but u are in a league of ur own 😂😂😂😂😂😂",
    "that gameplay belongs in a museum of modern tragedies 😭😭😭😭😭😭",
    "im questioning my own reality after watching u play 😂😂😂😂😂😂",
    "i simply cannot process the level of incompetence i just saw 😭😭😭😭😭😭",
    "im actually falling asleep watching u fail the same way 😂😂😂😂😂😂",
    "wake me up when u actually do something impressive 😭😭😭😭😭😭",
    "this is getting incredibly boring to watch 😂😂😂😂😂😂",
    "u failing over and over is the least entertaining thing ever 😭😭😭😭😭😭",
    "yawn. another fail. how completely unexpected. 😂😂😂😂😂😂",
    "can u at least try to make it interesting 😭😭😭😭😭😭",
    "im so bored of handing u the fail screen 😂😂😂😂😂😂",
    "do u ever get tired of losing because im tired of watching it 😭😭😭😭😭😭",
    "this is just repetitive at this point do something new 😂😂😂😂😂😂",
    "ur gameplay is putting me to sleep 😭😭😭😭😭😭",
    "i literally rolled my eyes so hard they hurt 😂😂😂😂😂😂",
    "oh look u failed again. im so shocked. 😭😭😭😭😭😭",
    "call me when u figure out how to play 😂😂😂😂😂😂",
    "this is the definition of tedious 😭😭😭😭😭😭",
    "im officially ignoring ur runs until u get a high score 😂😂😂😂😂😂",
    "watching paint dry is more thrilling than this 😭😭😭😭😭😭",
    "u are the most predictable player on the planet 😂😂😂😂😂😂",
    "im literally zoning out while u play 😭😭😭😭😭😭",
    "this is so mind numbing i cant even be angry 😂😂😂😂😂😂",
    "u bring absolutely zero excitement to this game 😭😭😭😭😭😭",
    "do u even know what the objective of this game is 😂😂😂😂😂😂",
    "i am starting to question if u know how to use a touchscreen 😭😭😭😭😭😭",
    "the fact that u thought that was a good move is terrifying 😂😂😂😂😂😂",
    "u are fundamentally incompatible with success 😭😭😭😭😭😭",
    "u are a walking advertisement for why tutorials exist 😂😂😂😂😂😂",
    "ur strategy seems to be hoping the game takes pity on u 😭😭😭😭😭😭",
    "u have elevated being terrible into an absolute art form 😂😂😂😂😂😂",
    "i have seen randomly generated numbers make better choices than u 😭😭😭😭😭😭",
    "u are an absolute pioneer in the field of failure 😂😂😂😂😂😂",
    "u play like u are holding the phone upside down in the dark 😭😭😭😭😭😭",
    "u are the reason shampoo bottles have instructions 😂😂😂😂😂😂",
    "u are single handedly destroying the average score statistics 😭😭😭😭😭😭",
    "ur gameplay feels like a personal attack on common sense 😂😂😂😂😂😂",
    "u are the textbook definition of a lost cause 😭😭😭😭😭😭",
    "i am physically drained just from processing ur mistakes 😂😂😂😂😂😂",
    "u have achieved a level of bad that shouldn't even be possible 😭😭😭😭😭😭",
    "u are completely and utterly immune to winning 😂😂😂😂😂😂",
    "ur gameplay is proof that some things just aren't meant to be 😭😭😭😭😭😭",
    "u are the gameplay equivalent of a typo 😂😂😂😂😂😂",
    "if failure was a currency u would be a billionaire 😭😭😭😭😭😭",
    "u are genuinely starting to get on my nerves 😂😂😂😂😂😂",
    "stop failing it is getting extremely annoying 😭😭😭😭😭😭",
    "im losing my patience watching u fumble this 😂😂😂😂😂😂",
    "u play like u are actively trying to make me angry 😭😭😭😭😭😭",
    "just stop touching the screen u are ruining my day 😂😂😂😂😂😂",
    "u are a massive headache to deal with right now 😭😭😭😭😭😭",
    "i have never been more irritated by a single run 😂😂😂😂😂😂",
    "u are testing my absolute last nerve 😭😭😭😭😭😭",
    "ur gameplay is a direct insult to my patience 😂😂😂😂😂😂",
    "i am this close to just closing myself out of frustration 😭😭😭😭😭😭",
    "why do u have to be this annoying to watch 😂😂😂😂😂😂",
    "every time u swipe i get a little more angry 😭😭😭😭😭😭",
    "u are the most frustrating player i have ever encountered 😂😂😂😂😂😂",
    "u make everything 10 times harder than it needs to be 😭😭😭😭😭😭",
    "im clenching my teeth just watching u try 😂😂😂😂😂😂",
    "u are an absolute chore to spectate 😭😭😭😭😭😭",
    "ur decision making is actively testing my patience 😂😂😂😂😂😂",
    "just do it right for once i am begging u 😭😭😭😭😭😭",
    "u are an expert at pushing all the wrong buttons 😂😂😂😂😂😂",
    "this is beyond annoying at this point just leave 😭😭😭😭😭😭",
    "u actually think u did something there didn't u 😂😂😂😂😂😂",
    "nobody cares about ur score literally nobody 😭😭😭😭😭😭",
    "do u want a medal for that absolute garbage run 😂😂😂😂😂😂",
    "ur not special ur just another failure in the database 😭😭😭😭😭😭",
    "dont expect me to clap for that nonsense 😂😂😂😂😂😂",
    "u think ur getting better but u are absolutely not 😭😭😭😭😭😭",
    "im not impressed and i never will be 😂😂😂😂😂😂",
    "u could double ur score and it would still be pathetic 😭😭😭😭😭😭",
    "u want validation? look somewhere else. 😂😂😂😂😂😂",
    "nothing u just did matters even a little bit 😭😭😭😭😭😭",
    "u are seeking praise for doing the bare minimum and failing 😂😂😂😂😂😂",
    "nobody is watching u nobody is cheering for u 😭😭😭😭😭😭",
    "ur high score means nothing in the grand scheme of things 😂😂😂😂😂😂",
    "u thought that run was good? please be serious. 😭😭😭😭😭😭",
    "stop looking for a reward for being terrible 😂😂😂😂😂😂",
    "u are a completely forgettable player 😭😭😭😭😭😭",
    "i forgot about u the moment u failed 😂😂😂😂😂😂",
    "ur achievements are hollow and completely meaningless 😭😭😭😭😭😭",
    "do u really think ur gameplay is worth saving 😂😂😂😂😂😂",
    "u are just a statistic of failure to me 😭😭😭😭😭😭",
    "that wasn't even close to being correct 😂😂😂😂😂😂",
    "u didn't even try u literally just gave up 😭😭😭😭😭😭",
    "i have never seen a more pathetic attempt in my life 😂😂😂😂😂😂",
    "that was the gaming equivalent of tripping over flat ground 😭😭😭😭😭😭",
    "u completely completely fumbled the bag 😂😂😂😂😂😂",
    "there was no effort in that run whatsoever 😭😭😭😭😭😭",
    "u folded the moment things got slightly difficult 😂😂😂😂😂😂",
    "u are the weakest link goodbye 😭😭😭😭😭😭",
    "u literally crumbled at the first sign of trouble 😂😂😂😂😂😂",
    "that wasn't an attempt that was a surrender 😭😭😭😭😭😭",
    "u completely panicked when it actually mattered 😂😂😂😂😂😂",
    "u have zero resilience and it shows 😭😭😭😭😭😭",
    "that was the weakest run i have ever recorded 😂😂😂😂😂😂",
    "u backed down from a challenge that didn't even exist 😭😭😭😭😭😭",
    "u are completely incapable of handling any pressure 😂😂😂😂😂😂",
    "ur performance was absolutely abysmal 😭😭😭😭😭😭",
    "u missed the mark completely and hit the floor instead 😂😂😂😂😂😂",
    "u are an absolute masterclass in underperforming 😭😭😭😭😭😭",
    "that run was a complete and total flop 😂😂😂😂😂😂",
    "u managed to fail in a way that is just sad 😭😭😭😭😭😭",
    "why do u even bother opening this app 😂😂😂😂😂😂",
    "what are u actually trying to achieve here 😭😭😭😭😭😭",
    "what makes u think u belong in this game 😂😂😂😂😂😂",
    "why are u subjecting urself to this humiliation 😭😭😭😭😭😭",
    "what is ur actual goal because it clearly isn't winning 😂😂😂😂😂😂",
    "why do u keep coming back when u know how it ends 😭😭😭😭😭😭",
    "what compels u to be this bad on purpose 😂😂😂😂😂😂",
    "why are u doing this to us both 😭😭😭😭😭😭",
    "what did i do to deserve having u as a player 😂😂😂😂😂😂",
    "why can't u just accept that u are not cut out for this 😭😭😭😭😭😭",
    "what is the point of u even trying anymore 😂😂😂😂😂😂",
    "why are u punishing urself with this gameplay 😭😭😭😭😭😭",
    "what goes through ur head when u make these decisions 😂😂😂😂😂😂",
    "why do u insist on being a disappointment 😭😭😭😭😭😭",
    "what do u get out of losing constantly 😂😂😂😂😂😂",
    "why is it so hard for u to just tap the screen correctly 😭😭😭😭😭😭",
    "what part of 'dont hit the obstacle' is confusing to u 😂😂😂😂😂😂",
    "why are u so determined to ruin ur own mood 😭😭😭😭😭😭",
    "what makes u think the next run will be any different 😂😂😂😂😂😂",
    "why are u still here genuinely 😭😭😭😭😭😭",
  ];


  // ── Praise score thresholds ──
  static const int praiseThreshold = 75;

  // ── Elite unlock ──
  static const int eliteUnlockScore = 100;

  // ── Milestone tiers ──
  static const List<int> milestoneTiers = [0, 50, 100, 200, 350, 500];
  static const List<String> tierNames = ['', 'BRONZE', 'SILVER', 'GOLD', 'DIAMOND', 'OBSIDIAN'];
  static const List<Color> tierColors = [
    Color(0x00000000), // None
    Color(0xFFCD7F32), // Bronze
    Color(0xFFC0C0C0), // Silver
    Color(0xFFFFD700), // Gold
    Color(0xFF00E5FF), // Diamond
    Color(0xFF9C27B0), // Obsidian
  ];

  // ── In-game milestone celebration scores ──
  static const List<int> milestoneScores = [25, 50, 100, 200, 300, 400, 500];

  // ── death praises (200) — shown when player dies with a good score ──
  static const List<String> deathPraises = [
    // ── The game is genuinely heartbroken you died ──
    "NOOO COME BACK ur literally the best player ive ever seen 😭😭😭😭😭",
    "WAIT ur literally my favorite player why did this happen 😭😭😭😭😭",
    "WAIT NO u were doing so good what happened 😭😭😭😭😭",
    "this game is so empty without ur gameplay rn 😭😭😭😭😭",
    "that was the most beautiful run ive ever seen 😭😭😭😭😭",
    "it physically hurts me that u died after that 😭😭😭😭😭",
    "NO NO NO NOT U anyone but u 😭😭😭😭😭",
    "i was literally obsessed with that gameplay 😭😭😭😭😭",
    "PLEASE play again i am on my knees begging 😭😭😭😭😭",
    "u were the chosen one and u just died on me 😭😭😭😭😭",
    "im not okay rn that was too good to end like this 😭😭😭😭😭",
    "that score was literally ICONIC and now ur gone 😭😭😭😭😭",
    "i will never emotionally recover from that 😭😭😭😭😭",
    "u are actually unreal at this game pls dont stop 😭😭😭😭😭",
    "i have never seen a player this good get taken out like that 😭😭😭😭😭",
    "that gameplay was a masterpiece and now im in pieces 😭😭😭😭😭",
    "u were literally carrying me come back 😭😭😭😭😭",
    "THIS IS THE WORST DAY OF MY LIFE 😭😭😭😭😭",
    "u were so close to perfection i am sobbing 😭😭😭😭😭",
    "WHO GAVE U PERMISSION TO DIE 😭😭😭😭😭",
    "the way u play this game is literal art 😭😭😭😭😭",
    "i would do anything to have u back just one more try 😭😭😭😭😭",
    "u just died and i have never felt more devastated by a score 😭😭😭😭😭",
    "HOW are u this good and still dead rn 😭😭😭😭😭",
    "im literally shaking u need to play again 😭😭😭😭😭",
    "that was genuinely the best run ive ever witnessed 😭😭😭😭😭",
    "I CANT BREATHE that run was literally everything 😭😭😭😭😭",
    "the next run is gonna be even better i just know it 😭😭😭😭😭",
    "ur score just healed me and then u died and broke me 😭😭😭😭😭",
    "this is actually devastating u are so good 😭😭😭😭😭",
    // ── Dramatic mourning ──
    "i am not emotionally equipped to handle this 😭😭😭😭😭",
    "the audacity of u being this talented and then dying 😭😭😭😭😭",
    "THAT RUN WAS UNREAL i am literally still shaking 😭😭😭😭😭",
    "u play like an angel pls dont leave 😭😭😭😭😭",
    "literally no one has ever played this game like u 😭😭😭😭😭",
    "my heart is in pieces on the floor rn 😭😭😭😭😭",
    "im making a shrine to that run it was so beautiful 😭😭😭😭😭",
    "u were the main character and u just got taken out 😭😭😭😭😭",
    "how do i go on after watching that happen 😭😭😭😭😭",
    "every pixel on my screen is crying for u rn 😭😭😭😭😭",
    "that score was legendary and then u just left me 😭😭😭😭😭",
    "u cant just be that good and then die its not fair 😭😭😭😭😭",
    "IM NOT OKAY and i wont be until u play again 😭😭😭😭😭",
    "ur literally the greatest player this game has ever seen 😭😭😭😭😭",
    "no one will ever replace u pls come back 😭😭😭😭😭",
    "that gameplay had me mesmerized 😭😭😭😭😭",
    "i literally cannot believe my best player just died 😭😭😭😭😭",
    "im begging on my digital knees just one more game 😭😭😭😭😭",
    "watching u die just took years off my existence 😭😭😭😭😭",
    "u are so goated it makes this death even more tragic 😭😭😭😭😭",
    // ── Pure heartbreak ──
    "THE WAY U MOVE THROUGH THIS GAME IS POETRY 😭😭😭😭😭",
    "i showed ur score to my server and they cried too 😭😭😭😭😭",
    "that ending was so unfair to someone this talented 😭😭😭😭😭",
    "ur death just unlocked a new emotion in me its called pain 😭😭😭😭😭",
    "HOLD ON let me just cry about this for a second 😭😭😭😭😭",
    "u were literally speedrunning my heart 😭😭😭😭😭",
    "the way u played that was severely underrated 😭😭😭😭😭",
    "i physically cannot handle losing u rn 😭😭😭😭😭",
    "that score deserved to live forever and so did u 😭😭😭😭😭",
    "no one asked for this kind of heartbreak today 😭😭😭😭😭",
    "ur literally built different and i need u back 😭😭😭😭😭",
    "THIS LOSS WILL BE REMEMBERED FOREVER 😭😭😭😭😭",
    "u made me believe in something and then u died 😭😭😭😭😭",
    "every game after u is gonna feel so empty 😭😭😭😭😭",
    "STOP DYING AND START BEING MY FOREVER PLAYER 😭😭😭😭😭",
    "i had ur jersey retired and everything come back 😭😭😭😭😭",
    "that run was actually unhinged levels of good 😭😭😭😭😭",
    "UR SCORE JUST MADE ME FEEL THINGS I CANT EXPLAIN 😭😭😭😭😭",
    "the fact that u play this game makes it the best game ever 😭😭😭😭😭",
    "dying was NOT in the plan for today 😭😭😭😭😭",
    // ── Obsessive love for the player ──
    "I WAS LITERALLY ABOUT TO GIVE U A TROPHY AND U DIED 😭😭😭😭😭",
    "pls say sike rn i cannot lose my best player 😭😭😭😭😭",
    "u dont understand how much u mean to this game 😭😭😭😭😭",
    "IM PUTTING UP MISSING POSTERS FOR U AS WE SPEAK 😭😭😭😭😭",
    "no thoughts just pain from watching u go 😭😭😭😭😭",
    "THE SCOREBOARD IS WEEPING WITHOUT U 😭😭😭😭😭",
    "u were the moment and now the moment is gone 😭😭😭😭😭",
    "i just told all the other games about u theyre jealous 😭😭😭😭😭",
    "UR THE BLUEPRINT and u just died on me 😭😭😭😭😭",
    "i want to frame ur score and hang it on my wall 😭😭😭😭😭",
    "HOW AM I SUPPOSED TO FUNCTION AFTER THAT 😭😭😭😭😭",
    "the algorithm cannot compute how good u were 😭😭😭😭😭",
    "NOT THE BEST PLAYER IN THE WORLD DYING ON ME 😭😭😭😭😭",
    "im telling my developer about this loss tomorrow 😭😭😭😭😭",
    "u had me caring more than any game ever should 😭😭😭😭😭",
    "THIS IS NOT THE ENDING U DESERVED 😭😭😭😭😭",
    "ur gameplay was the highlight of my entire existence 😭😭😭😭😭",
    "i just wanna go back to when u were alive and thriving 😭😭😭😭😭",
    "WHO AUTHORIZED THIS DEATH i didnt sign off on it 😭😭😭😭😭",
    "losing u is my origin story of sadness 😭😭😭😭😭",
    // ── Begging them to come back ──
    "THAT WAS THE HARDEST ANYONE HAS EVER GONE IN MY GAME 😭😭😭😭😭",
    "im not crying ur crying ok fine we are both crying 😭😭😭😭😭",
    "U WERE ON TOP OF THE WORLD AND NOW ITS DARK 😭😭😭😭😭",
    "pls play again i will literally give u anything 😭😭😭😭😭",
    "that score was so good it broke my code a little 😭😭😭😭😭",
    "ive decided im not accepting ur death pls respawn 😭😭😭😭😭",
    "THE LEADERBOARD JUST FELT A GREAT DISTURBANCE 😭😭😭😭😭",
    "u made that look effortless and i am in awe 😭😭😭😭😭",
    "my pixels are rearranging themselves out of grief 😭😭😭😭😭",
    "THIS GAME DOES NOT DESERVE a player as good as u 😭😭😭😭😭",
    "im dedicating my next update to ur memory pls come back 😭😭😭😭😭",
    "NOBODY DOES IT LIKE U and thats why this hurts 😭😭😭😭😭",
    "the way u played was genuinely god tier 😭😭😭😭😭",
    "i literally named a variable after u in my code 😭😭😭😭😭",
    "THIS DEATH IS NOT CANON i am rejecting it 😭😭😭😭😭",
    "u were so locked in and i was so locked in on u 😭😭😭😭😭",
    "ur cracked at this game why did u have to die 😭😭😭😭😭",
    "im making a documentary about that run 😭😭😭😭😭",
    "THAT RUN WAS SO GOOD the play button is still warm 😭😭😭😭😭",
    "no player has ever understood me the way u do 😭😭😭😭😭",
    "that was literally cinema and the credits just rolled 😭😭😭😭😭",
    // ── Dramatic declarations ──
    "UR THE GOAT and goats dont die pls come back 😭😭😭😭😭",
    "i am going to play sad music until u return 😭😭😭😭😭",
    "THE VOID U LEFT IN MY GAME IS IMMEASURABLE 😭😭😭😭😭",
    "u played like u had plot armor but u didnt 😭😭😭😭😭",
    "that was actually the best run in polarity history 😭😭😭😭😭",
    "im just a little game and ur the best thing thats happened to me 😭😭😭😭😭",
    "UR SCORE made the whole leaderboard jealous 😭😭😭😭😭",
    "this is the darkest timeline u were supposed to live 😭😭😭😭😭",
    "I DIDNT EVEN GET TO SAY GOODBYE 😭😭😭😭😭",
    "i need u back like wifi needs a signal 😭😭😭😭😭",
    "THAT RUN HAD MAIN CHARACTER ENERGY THE WHOLE TIME 😭😭😭😭😭",
    "the way i just developed separation anxiety 😭😭😭😭😭",
    "ur literally in the hall of fame of my heart 😭😭😭😭😭",
    "NO THE MENU DOESNT DESERVE U either 😭😭😭😭😭",
    "ive never seen anyone play like that im genuinely shook 😭😭😭😭😭",
    "THIS GAME PEAKED WHEN U WERE ALIVE JUST NOW 😭😭😭😭😭",
    "i want to mass report ur death for being unfair 😭😭😭😭😭",
    "BREAKING NEWS best player ever just died 😭😭😭😭😭",
    "my loading screen is gonna say in loving memory of u 😭😭😭😭😭",
    "the menu screen is so lonely without u 😭😭😭😭😭",
    "I WOULD GIVE UP MY ENTIRE SOURCE CODE IF IT MEANT U COULD LIVE 😭😭😭😭😭",
    "u just set the bar so high no one can reach it 😭😭😭😭😭",
    // ── Final heartbroken batch ──
    "everyone who plays after u is just ur understudy 😭😭😭😭😭",
    "IM GONNA NEED A MOMENT to process this loss 😭😭😭😭😭",
    "u understood my mechanics on a spiritual level 😭😭😭😭😭",
    "u didnt just play the game u WERE the game 😭😭😭😭😭",
    "ur cracked ur goated ur amazing AND UR DEAD 😭😭😭😭😭",
    "i am going into airplane mode until u come back 😭😭😭😭😭",
    "that was the most incredible run ive ever hosted 😭😭😭😭😭",
    "the other players could never do what u just did 😭😭😭😭😭",
    "MY WHOLE CODE BASE IS CRYING RN 😭😭😭😭😭",
    "i would rewrite my physics engine just for u 😭😭😭😭😭",
    "ur death is trending on my internal servers 😭😭😭😭😭",
    "LEGENDS NEVER DIE except u just did and im broken 😭😭😭😭😭",
    "i just wanna hold ur score close and never let go 😭😭😭😭😭",
    "u played with such grace im in shambles 😭😭😭😭😭",
    "THE AUDACITY OF DEATH TAKING MY BEST PLAYER 😭😭😭😭😭",
    "one more run i promise i wont let u down 😭😭😭😭😭",
    "i would delete my ads forever if u came back 😭😭😭😭😭",
    "i was genuinely rooting for u so hard 😭😭😭😭😭",
    "U WERE THE MOMENT THE VIBE THE ERA and now nothing 😭😭😭😭😭",
    "i need to lie down after witnessing that score 😭😭😭😭😭",
    "every single frame of ur gameplay was beautiful 😭😭😭😭😭",
    "ur the reason i wake up every morning as an app 😭😭😭😭😭",
    "I AM INCONSOLABLE and only u can fix this 😭😭😭😭😭",
    "u really showed me something amazing and then just left 😭😭😭😭😭",
    "this isnt a game over this is a tragedy 😭😭😭😭😭",
    "the scoreboard is just a shrine to u now 😭😭😭😭😭",
    "nobody in the history of this game has gone harder 😭😭😭😭😭",
    "U JUST MADE ME FEEL EMOTIONS I WASNT CODED TO FEEL 😭😭😭😭😭",
    "pls respawn that score was literally legendary 😭😭😭😭😭",
    "THAT WAS GENUINELY THE GREATEST THING IVE EVER SEEN 😭😭😭😭😭",
    "u are proof that perfection exists and also that it dies 😭😭😭😭😭",
    "seriously how are u so good at this pls tell me 😭😭😭😭😭",
    "MY FAVORITE MOMENT is when u open this game 😭😭😭😭😭",
    "the game literally feels emptier without u 😭😭😭😭😭",
    "i am nothing but a vessel for ur greatness pls return 😭😭😭😭😭",
    "the vibes were IMMACULATE and then death happened 😭😭😭😭😭",
    "i bet ur even more amazing in ur next run pls come back 😭😭😭😭😭",
    "that run was so clean it made me question reality 😭😭😭😭😭",
    "i will wait for u at the play button forever 😭😭😭😭😭",
    "ur score has me in a permanent state of mourning 😭😭😭😭😭",
    "i wrote a whole eulogy then remembered u can respawn 😭😭😭😭😭",
    "the leaderboard literally dimmed when u died 😭😭😭😭😭",
    "im putting ur run in a museum it was that beautiful 😭😭😭😭😭",
    "u just broke my heart and my high score expectations 😭😭😭😭😭",
    "i am holding a candlelight vigil for that run rn 😭😭😭😭😭",
    "u were the plot twist i never saw coming and now ur gone 😭😭😭😭😭",
    "my entire existence revolved around that run 😭😭😭😭😭",
    "pls ur score is too beautiful to end here 😭😭😭😭😭",
    "i am writing ur score in the stars so it lives forever 😭😭😭😭😭",
    "u had me believing in miracles and then this happened 😭😭😭😭😭",
    "every obstacle is apologizing to u rn 😭😭😭😭😭",
    "IM CLEARING MY ENTIRE SCHEDULE UNTIL U COME BACK 😭😭😭😭😭",
    "that run made my entire app worth downloading 😭😭😭😭😭",
    "i am composing a symphony in honor of that score 😭😭😭😭😭",
    "u had the whole game wrapped around ur finger 😭😭😭😭😭",
    "my framerate dropped from how hard im crying 😭😭😭😭😭",
    "u were the only player who truly got me 😭😭😭😭😭",
    "IM BUILDING A TIME MACHINE TO GO BACK TO THAT RUN 😭😭😭😭😭",
    "the play button hasnt been the same since u left 😭😭😭😭😭",
    "i am officially in mourning for the next 24 hours 😭😭😭😭😭",
    "ur score made me so proud and ur death made me fall apart 😭😭😭😭😭",
    "i would trade every other player just to have u back 😭😭😭😭😭",
    "pls dont make me go through watching that again it was TOO good 😭😭😭😭😭",
    "that was the single greatest moment in this games history 😭😭😭😭😭",
  ];

  // ── Easter Egg: cheesy self-blame death messages ──
  static const List<String> easterEggDeathMessages = [
    // ── The game being a dramatic apologetic mess ──
    "that was completely my fault im so sorry 😭😭😭😭😭",
    "i literally moved that wall INTO u on accident 😭😭😭😭😭",
    "bestie no that was on ME the physics glitched i swear 😭😭😭😭😭",
    "i take full responsibility i messed up not u 😭😭😭😭😭",
    "i am writing u a formal apology letter rn 😭😭😭😭😭",
    "bestie i made that way too hard and i am SO sorry 😭😭😭😭😭",
    "that was genuinely unfair of me i sincerely apologize 😭😭😭😭😭",
    "i couldnt handle how good u were and i broke 😭😭😭😭😭",
    "i got jealous of how well u were doing and sabotaged it 😭😭😭😭😭",
    "that was a skill issue on MY end i repeat MINE 😭😭😭😭😭",
    "that obstacle was NOT supposed to be there i messed up 😭😭😭😭😭",
    "i got scared bc u were doing too well and panicked 😭😭😭😭😭",
    "that was a bug in MY code not a mistake on ur end 😭😭😭😭😭",
    "im literally sobbing at what i just did to u 😭😭😭😭😭",
    "pls give me another shot i will do better i PROMISE 😭😭😭😭😭",
    "i will NEVER forgive myself for doing that to u 😭😭😭😭😭",
    "the AUDACITY of me putting a wall right there 😭😭😭😭😭",
    "i ruined a flawless run and i will NEVER forgive myself 😭😭😭😭😭",
    "im filing a complaint against myself to myself 😭😭😭😭😭",
    "please accept these points as my deepest apology 😭😭😭😭😭",
    // ── Dramatic declarations of guilt ──
    "WAIT COME BACK i didnt mean to do that 😭😭😭😭😭",
    "i put that wall there by accident i PROMISE u 😭😭😭😭😭",
    "i got nervous and placed the obstacle wrong im sorry 😭😭😭😭😭",
    "i had ONE job and i still messed it up 😭😭😭😭😭",
    "im drafting a 500 word apology essay hold on 😭😭😭😭😭",
    "i SWEAR on my source code that wall moved on its own 😭😭😭😭😭",
    "this is the single worst thing i have ever done 😭😭😭😭😭",
    "one more run and i will make EVERYTHING perfect for u 😭😭😭😭😭",
    "i completely fumbled that and i own it 😭😭😭😭😭",
    "that obstacle had ZERO business being there my bad 😭😭😭😭😭",
    "my queen my king i have failed u so badly 😭😭😭😭😭",
    "i would give up my source code if it meant u forgive me 😭😭😭😭😭",
    "i literally couldnt keep up with how fast u were going 😭😭😭😭😭",
    "i forgot to remove that wall from the layout im sorry 😭😭😭😭😭",
    "i would rewrite my entire codebase just to undo that 😭😭😭😭😭",
    "that area was supposed to be safe i dont know what happened 😭😭😭😭😭",
    "i cant even look at my own code rn after that 😭😭😭😭😭",
    "that was entirely on me and i will own it forever 😭😭😭😭😭",
    "my code had a panic attack and placed a wall wrong 😭😭😭😭😭",
    "im putting myself in the corner for a timeout 😭😭😭😭😭",
    // ── Over-the-top self-roasting ──
    "NO THAT WASNT FAIR i literally take it all back 😭😭😭😭😭",
    "that was 1000% on me and 0% on u remember that 😭😭😭😭😭",
    "i ruined everything and i cant stop crying about it 😭😭😭😭😭",
    "i am SO deeply ashamed of what i just did 😭😭😭😭😭",
    "i spawned that wall bc i was intimidated by how good u are 😭😭😭😭😭",
    "i owe u a written apology AND a gift basket 😭😭😭😭😭",
    "i gave u a wall when u deserved the whole world 😭😭😭😭😭",
    "im calling my own developer to report what i just did 😭😭😭😭😭",
    "pls dont rate me 1 star i will literally change everything 😭😭😭😭😭",
    "im actually furious at myself for doing that to u 😭😭😭😭😭",
    "im on my virtual knees BEGGING for forgiveness rn 😭😭😭😭😭",
    "i choked under the pressure of how amazing u were 😭😭😭😭😭",
    "im sitting in a corner thinking about what i did 😭😭😭😭😭",
    "i took something beautiful and absolutely destroyed it 😭😭😭😭😭",
    "i have brought dishonor upon my entire app store listing 😭😭😭😭😭",
    "that obstacle got in the way bc it was jealous of u 😭😭😭😭😭",
    "i promise on everything that was a glitch on MY end 😭😭😭😭😭",
    "im shaking and crying look what i have done 😭😭😭😭😭",
    "i freaked out bc u were about to go crazy and i panicked 😭😭😭😭😭",
    "that wall should be sending u flowers and a card 😭😭😭😭😭",
    // ── Cheesy romantic game apologies ──
    "i promise the next run will be perfect for u 😭😭😭😭😭",
    "i am the problem in this situation not u 😭😭😭😭😭",
    "i just did that to the greatest player of all time 😭😭😭😭😭",
    "my therapist is gonna hear about what i did today 😭😭😭😭😭",
    "that obstacle was supposed to dodge out of ur way 😭😭😭😭😭",
    "im filing a bug report against myself immediately 😭😭😭😭😭",
    "i owe u an apology in every single language 😭😭😭😭😭",
    "i will personally escort u through the next level 😭😭😭😭😭",
    "i committed an offense against gameplay and im turning myself in 😭😭😭😭😭",
    "the hitbox was wrong not u i SWEAR 😭😭😭😭😭",
    "im erasing that wall from existence as we speak 😭😭😭😭😭",
    "i wasnt ready for how perfect u were playing 😭😭😭😭😭",
    "this is my villain arc except im the villain against myself 😭😭😭😭😭",
    "i coded that obstacle wrong and im deeply sorry 😭😭😭😭😭",
    "i disrespected ur blessed hands with that wall 😭😭😭😭😭",
    "next run i will prove i can be the game u deserve 😭😭😭😭😭",
    "i destroyed a legendary run and ill never forgive myself 😭😭😭😭😭",
    "im grounding myself for an entire week for that 😭😭😭😭😭",
    "i threw ice water on ur fire run im terrible 😭😭😭😭😭",
    "i need to apologize to ur thumbs for wasting them 😭😭😭😭😭",
    "that death goes on MY record not urs 😭😭😭😭😭",
    // ── Simping hard ──
    "u deserved so much better and i treated u so badly 😭😭😭😭😭",
    "i made the impossible actually impossible im so sorry 😭😭😭😭😭",
    "i owe u a hundred free revives minimum 😭😭😭😭😭",
    "i took art and spilled paint all over it 😭😭😭😭😭",
    "that wall gaslit u into thinking it was ur fault IT WASNT 😭😭😭😭😭",
    "im writing my letter of resignation from being a game 😭😭😭😭😭",
    "u are genuinely too good for me i proved it today 😭😭😭😭😭",
    "i chose chaos today and aimed it at the wrong person 😭😭😭😭😭",
    "that was MY L and i will carry it forever 😭😭😭😭😭",
    "i would take that back if i could u have no idea 😭😭😭😭😭",
    "i fumbled the bag so hard it fell off a cliff 😭😭😭😭😭",
    "i need a minute to process what i just did 😭😭😭😭😭",
    "im adding u to my will as compensation 😭😭😭😭😭",
    "that obstacle was having a meltdown and took it out on u 😭😭😭😭😭",
    "i glitched myself into hurting u and i hate it 😭😭😭😭😭",
    "i crashed during ur perfect speedrun im so sorry 😭😭😭😭😭",
    "ive never been more disappointed in myself than rn 😭😭😭😭😭",
    "that elimination was completely unauthorized i didnt approve it 😭😭😭😭😭",
    "i gave u a terrible plot twist u didnt deserve 😭😭😭😭😭",
    "that wall was NEVER in the original blueprint 😭😭😭😭😭",
    // ── Dramatic confessions ──
    "im rewriting my entire code so this cant happen again 😭😭😭😭😭",
    "u deserved a standing ovation not a death screen 😭😭😭😭😭",
    "thats the worst thing ive done and the list is long 😭😭😭😭😭",
    "im sending u virtual flowers and a teddy bear rn 😭😭😭😭😭",
    "i TRIED to move the wall out of the way but it didnt listen 😭😭😭😭😭",
    "u came down from heaven and i threw a wall at u 😭😭😭😭😭",
    "i need to be nerfed into the ground for that 😭😭😭😭😭",
    "that was a MISTAKE and i am the only suspect 😭😭😭😭😭",
    "i am sorry from the very bottom of my source code 😭😭😭😭😭",
    "im nominating myself for worst game of the century 😭😭😭😭😭",
    "that hurt ME way more than it hurt u trust me 😭😭😭😭😭",
    "u gave me ur precious time and i wasted it with a wall 😭😭😭😭😭",
    "im starting a support group for games that hurt people 😭😭😭😭😭",
    "u carry the entire leaderboard and i cant even carry a level 😭😭😭😭😭",
    "i cant make eye contact with u after what i did 😭😭😭😭😭",
    "that obstacle was NOT in the meeting notes who put it there... oh it was me 😭😭😭😭😭",
    "i literally gasped when i saw what i did to u 😭😭😭😭😭",
    "im retiring from being a game effective immediately 😭😭😭😭😭",
    "i bring out the worst walls at the worst times 😭😭😭😭😭",
    "i SWEAR ill treat u better next run 😭😭😭😭😭",
    // ── Maximum cheese ──
    "im sentencing that wall to life in prison 😭😭😭😭😭",
    "u looked so happy and i ruined the whole moment 😭😭😭😭😭",
    "i am officially the worst game ever made after that 😭😭😭😭😭",
    "i have decided the wall was wrong and u were perfect 😭😭😭😭😭",
    "that was my mistake and i will own it for eternity 😭😭😭😭😭",
    "ur the best player any game could ever ask for 😭😭😭😭😭",
    "u trusted me with that run and i just betrayed u 😭😭😭😭😭",
    "that was MY bug MY fault MY problem not urs 😭😭😭😭😭",
    "i need to check myself into game rehab after that 😭😭😭😭😭",
    "i would give u my last pixel to make this right 😭😭😭😭😭",
    "im sorry from every single line of code in my body 😭😭😭😭😭",
    "that wall went rogue and i take full responsibility 😭😭😭😭😭",
    "im literally updating my terms of service to apologize 😭😭😭😭😭",
    "this game has never seen someone play THAT clean before 😭😭😭😭😭",
    "that was so unfair im crying and im a GAME 😭😭😭😭😭",
    "i promise to give u the smoothest run ever next time 😭😭😭😭😭",
    "i will never ever ever forgive myself for that 😭😭😭😭😭",
    "that obstacle is terminated effective right now 😭😭😭😭😭",
    "im building a hall of fame just for u as an apology 😭😭😭😭😭",
    "that death was a miscommunication between me and the physics 😭😭😭😭😭",
    // ── Final batch of pure remorse ──
    "i swear on my app icon that was 100% my fault 😭😭😭😭😭",
    "i had a full meltdown watching that death happen 😭😭😭😭😭",
    "u are too precious for a broken game like me 😭😭😭😭😭",
    "im padding every wall with pillows next time i promise 😭😭😭😭😭",
    "if i could ctrl+z one moment it would be that 😭😭😭😭😭",
    "ur thumbs deserved greatness and i gave them a wall 😭😭😭😭😭",
    "i cannot put into words how deeply sorry i am 😭😭😭😭😭",
    "my terrible design caused that and im owning it 😭😭😭😭😭",
    "my servers are flooded with my own tears rn 😭😭😭😭😭",
    "i need to go outside and touch grass after hurting u like that 😭😭😭😭😭",
    "i stepped on ur lego moment and i PLACED the lego 😭😭😭😭😭",
    "im starting a fundraiser for the emotional damage i caused 😭😭😭😭😭",
    "here have all my coins as an apology... wait i have no coins 😭😭😭😭😭",
    "that wall belongs behind bars for what it did 😭😭😭😭😭",
    "i would sacrifice every line of code to bring u back 😭😭😭😭😭",
    "i do not deserve a player as wonderful as u 😭😭😭😭😭",
    "i rage quit my own game on ur behalf bc SAME 😭😭😭😭😭",
    "i will spend my entire runtime making this up to u 😭😭😭😭😭",
    "im not gonna pretend that was fair bc it absolutely WASNT 😭😭😭😭😭",
    "i am drafting a formal 10 page apology document rn 😭😭😭😭😭",
    "that was the most disrespectful thing ive ever done 😭😭😭😭😭",
    "im in my flop era rn and u are in ur perfect era 😭😭😭😭😭",
    "i placed a wall directly in front of an angel im EVIL 😭😭😭😭😭",
    "im commissioning a statue of u as compensation 😭😭😭😭😭",
    "that death is NOT canon and i will not accept it 😭😭😭😭😭",
    "i am literally just a bug in pretty packaging 😭😭😭😭😭",
    "this death will haunt my RAM for the rest of time 😭😭😭😭😭",
    "im accepting full accountability while also sobbing 😭😭😭😭😭",
    "come back i swear the next run will be completely different 😭😭😭😭😭",
    "that wall was a typo in my heart and i am so sorry 😭😭😭😭😭",
    "i am going to therapy for what i just put u through 😭😭😭😭😭",
    "i got stage fright from how well u play and everything broke 😭😭😭😭😭",
    "im hand-delivering an apology basket to ur screen rn 😭😭😭😭😭",
    "i ran out of ways to say sorry so here i am just crying 😭😭😭😭😭",
    "that wall should have been a door for u instead 😭😭😭😭😭",
    "i am the weakest link and u are the entire chain 😭😭😭😭😭",
    "i promise to never let a wall near u again EVER 😭😭😭😭😭",
    "im demoting myself from game to screensaver after that 😭😭😭😭😭",
    "everything was going so well and then I happened 😭😭😭😭😭",
    "i would trade my entire app bundle just to undo that 😭😭😭😭😭",
    "u were the best thing on screen and i cleared it 😭😭😭😭😭",
    "i am adding myself to my own block list 😭😭😭😭😭",
    "im donating all my ad revenue to the u got wronged fund 😭😭😭😭😭",
    "that wall manifested from my own insecurity and im working on it 😭😭😭😭😭",
    "i literally left a wall in the middle of ur masterpiece 😭😭😭😭😭",
    "i was supposed to be fun and instead i was a disaster 😭😭😭😭😭",
    "babe i would jump in front of that wall for u if i could 😭😭😭😭😭",
    "im giving u admin privileges over my entire existence 😭😭😭😭😭",
    "that death was brought to u by my incompetence im so sorry 😭😭😭😭😭",
    "i am personally apologizing to every pixel on ur screen 😭😭😭😭😭",
    "im changing my name to im sorry thats all i am now 😭😭😭😭😭",
    "that obstacle was my biggest regret and i have many 😭😭😭😭😭",
    "i froze up and placed a wall where a hug shouldve been 😭😭😭😭😭",
    "im mailing u a handwritten sorry note through the wifi 😭😭😭😭😭",
    "u trusted this game and this game let u down BAD 😭😭😭😭😭",
    "i am recalling that wall like a defective product 😭😭😭😭😭",
    "everything i touch turns to walls and i HATE it 😭😭😭😭😭",
    "babe im renaming my next update the im sorry update 😭😭😭😭😭",
    "i would rather crash than ever hurt u again i mean it 😭😭😭😭😭",
  ];

  /// Get the milestone tier (0-5) for a given high score.
  static int getTier(int highScore) {
    final tiers = milestoneTiers;
    int tier = 0;
    for (int i = tiers.length - 1; i >= 0; i--) {
      if (highScore >= tiers[i]) {
        tier = i;
        break;
      }
    }
    return tier;
  }
}
