import 'dart:ui';

class GameConstants {
  GameConstants._();

  // ── Physics ──
  static const double baseMagnetForce = 2600.0;
  static const double maxHorizontalSpeed = 920.0;
  static const double playerRadius = 10.0;

  // ── Obstacle generation ──
  static const double obstacleMinThickness = 14.0;
  static const double obstacleMaxThickness = 22.0;
  static const double obstacleSpacing = 200.0;
  static const double obstacleSpacingJitter = 0.20; // ±20% random variance
  static const double baseScrollSpeed = 220.0;

  // Per-phase obstacle spacing multiplier (lower = denser = harder)
  static const List<double> phaseSpacingMultipliers = [
    1.15, // Phase 1: comfortable warmup
    1.00, // Phase 2: real game pace
    0.86, // Phase 3: tight rhythm
    0.74, // Phase 4: relentless
    0.64, // Phase 5: god-tier density
  ];

  // Per-phase max consecutive same-side obstacles (enforced in game_engine)
  // Phase 1-2: 2, Phase 3-4: 3, Phase 5: 4

  // ── Safe spawn delay (seconds before first obstacle) ──
  static const double safeSpawnDelay = 0.8;

  // ── 5 Visual & Difficulty Phases ──
  // Phase 1: 0-40    Pure White on Pitch Black (warmup)
  // Phase 2: 41-120  Electric Blue (real game starts)
  // Phase 3: 121-250 Warning Yellow (tighter, faster snaps)
  // Phase 4: 251-420 Crimson Red (brutal, narrow gaps)
  // Phase 5: 421+    Inverted (white bg / black geo), max everything
  static const List<int> phaseThresholds = [0, 50, 130, 260, 430];

  static const List<Color> phaseColors = [
    Color(0xFFFFFFFF), // Phase 1: Pure White
    Color(0xFF007AFF), // Phase 2: Electric Blue
    Color(0xFFFFD60A), // Phase 3: Warning Yellow
    Color(0xFFFF3B30), // Phase 4: Crimson Red
    Color(0xFF000000), // Phase 5: Black (inverted theme)
  ];

  // Speed multipliers per phase (scroll speed × this)
  static const List<double> phaseSpeedMultipliers = [
    1.0, 1.18, 1.40, 1.65, 1.92,
  ];

  // Magnet multipliers (lateral pull × this)
  static const List<double> phaseMagnetMultipliers = [
    0.55, 0.72, 0.92, 1.15, 1.40,
  ];

  // Gap shrink factors per phase (1.0 = widest, lower = narrower gaps)
  static const List<double> phaseGapFactors = [
    1.0, 0.88, 0.74, 0.62, 0.52,
  ];

  // ── Shield ──
  // First shield at 20, second at 60, then x2 each time
  static const int firstShieldScore = 20;
  static const int secondShieldScore = 60;
  static const double shieldInvincibilityDuration = 3.0;

  // ── Ads (Time-only Lock) ──
  static const int interstitialMinIntervalSeconds = 70;
  static const double iapPrice = 2.99;
  static const String iapProductId = 'remove_ads';

  // AdMob IDs can be overridden with --dart-define for production.
  static const String androidAppId = String.fromEnvironment(
    'ANDROID_ADMOB_APP_ID',
    defaultValue: 'ca-app-pub-4151123662328725~3767987674',
  );
  static const String iosAppId = String.fromEnvironment(
    'IOS_ADMOB_APP_ID',
    defaultValue: 'ca-app-pub-3940256099942544~1458002511', // TODO: replace with iOS production ID
  );

  static const String androidBannerId = String.fromEnvironment(
    'ANDROID_BANNER_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-3940256099942544/6300978111',
  );
  static const String iosBannerId = String.fromEnvironment(
    'IOS_BANNER_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-3940256099942544/2934735716',
  );
  static const String androidInterstitialId = String.fromEnvironment(
    'ANDROID_INTERSTITIAL_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-4151123662328725/3311844641',
  );
  static const String iosInterstitialId = String.fromEnvironment(
    'IOS_INTERSTITIAL_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-3940256099942544/4411468910',
  );
  static const String androidRewardedId = String.fromEnvironment(
    'ANDROID_REWARDED_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-4151123662328725/6877578771',
  );
  static const String iosRewardedId = String.fromEnvironment(
    'IOS_REWARDED_AD_UNIT_ID',
    defaultValue: 'ca-app-pub-3940256099942544/1712485313',
  );

  // Leaderboard IDs. Override with --dart-define.
  static const String androidLeaderboardId = String.fromEnvironment(
    'ANDROID_LEADERBOARD_ID',
    defaultValue: 'CgkI8OfvjJcWEAIQAQ',
  );
  static const String iosLeaderboardId = String.fromEnvironment(
    'IOS_LEADERBOARD_ID',
    defaultValue: 'polarity_leaderboard',
  );

  // ── Revive ──
  static const double reviveInvincibilityDuration = 3.0;
  static const int reviveCountdownSeconds = 3;

  // ── Tutorial ──
  static const int tutorialFadeScore = 5;

  // ── Review ──
  static const int minScoreForReview = 20;

  // ── Privacy ──
  static const String privacyPolicyUrl = 'https://polarityprivacy.netlify.app/';

  // ── death roasts (300) ──
  static const List<String> deathRoasts = [
    "don't u dare press restart 😂😂😂😂😂",
    "shoo shoo GO away from my game 😂😂😂😂😂😂",
    "just put the phone down bro 😂😂😂😂😂",
    "u and i both know u shouldn't press it 😂😂😂",
    "don't. don't u do it 😭😭😭😭😭",
    "ur literally never learning ur lesson 😂😂😂😂",
    "bro is gonna press it 😭😭😭😭😭😭",
    "u already know how this ends 😂😂😂😂😂",
    "pls don't tell anyone u play this game 😂😂😂😂😂😂😂",
    "bro actually downloaded this 😂😂😂😂😂",
    "haww 😂😂😂😂😂",
    "cry about it 😂😂😂😂😂",
    "u okay 😂😂😂😂😂",
    "gonna cry or nah 😂😂😂😂😂😂",
    "cry harder 😂😂😂😂😂",
    "u still here 😭😭😭😭😭",
    "cry about it no one cares 😂😂😂😂😂😂",
    "u felt that 😭😭😭😭😭😭",
    "go cry somewhere 😂😂😂😂😂",
    "u really believed in urself 😂😂😂😂😂😂😂😂😂😂",
    "cry about it and then cry again 😂😂😂😂😂",
    "go ahead cry 😂😂😂😂😂😂",
    "this is so sad for u 😭😭😭😭😭😭",
    "cry about it it's fine 😂😂😂😂😂",
    "delete this game 😂😂😂😂😂",
    "just delete it 😭😭😭😭😭",
    "u need to delete this rn 😂😂😂😂😂😂",
    "u should've deleted this yesterday 😂😂😂😂😂",
    "delete it ur doing urself a favour 😭😭😭😭😭",
    "just delete it bro 😂😂😂😂😂😂",
    "u really need to delete this 😂😂😂😂😂",
    "😂😂😂😂😂😂😂😂😂",
    "😂😂😂😂😂😂😂",
    "😂😂😂😂😂😂😂😂😂😂",
    "😂😂😂😂😂😂",
    "😂😂😂😂😂😂😂😂",
    "😂😂😂😂😂😂😂😂😂😂😂",
    "😂😂😂😂😂😂😂",
    "😂😂😂😂😂😂😂😂😂",
    "😂😂😂😂😂😂😂😂😂😂😂😂",
    "😂😂😂😂😂😂😂😂",
    "i would uninstall myself specifically from ur phone if i could 😭😭😭😭😭",
    "i have been on better phones 😭😭😭😭😭😭",
    "u are not the user i deserved 😂😂😂😂😂",
    "i expected so much more from u 😂😂😂😂😂😂",
    "this is not what i was designed for 😭😭😭😭😭😭",
    "u are genuinely my worst user 😂😂😂😂😂",
    "what did i do to deserve u as a player 😭😭😭😭😭",
    "i was a good game before u showed up 😂😂😂😂😂",
    "i have never been played this badly 😂😂😂😂😂😂",
    "i was doing fine before u downloaded me 😂😂😂😂😂",
    "other players don't do this to me 😭😭😭😭😭😭",
    "what did i ever do to u 😂😂😂😂😂😂",
    "i deserved a better player than this 😭😭😭😭😭",
    "why u 😂😂😂😂😂",
    "please leave me alone 😭😭😭😭😭",
    "i'm begging u to stop 😂😂😂😂😂",
    "please just put the phone down 😭😭😭😭😭😭",
    "i can't do this anymore 😂😂😂😂😂😂",
    "please i have a family 😭😭😭😭😭",
    "i'm so tired of u 😂😂😂😂😂",
    "please find another game 😭😭😭😭😭😭",
    "why won't u just leave me alone 😂😂😂😂😂",
    "yeah go ahead blame the game 😂😂😂😂😂",
    "yeah blame me sure 😂😂😂😂😂😂",
    "yeah the game is the problem 😂😂😂😂😂",
    "sure blame everyone but urself 😭😭😭😭😭",
    "yeah go ahead i'm used to it 😂😂😂😂😂😂",
    "yeah blame the game that's so u 😂😂😂😂😂",
    "sure it's my fault ur like this 😭😭😭😭😭",
    "have u no shame 😂😂😂😂😂",
    "the shamelessness is actually crazy 😭😭😭😭😭",
    "absolutely zero shame 😂😂😂😂😂",
    "literally begging u to have some shame 😭😭😭😭😭",
    "are u not embarrassed 😂😂😂😂😂😂",
    "the fact that u are still trying is shameless 😭😭😭😭😭",
    "shamelessly pressing restart again 😂😂😂😂😂😂",
    "u are a living, breathing skill issue 😂😂😂😂😂",
    "imagine trying this hard and still failing 😂😂😂😂😂😂",
    "i am actually second-hand embarrassed for u 😭😭😭😭😭",
    "ur whole existence is a misclick 😂😂😂😂😂",
    "u should be paying me to watch u play this badly 😭😭😭😭😭",
    "even the tutorial was disappointed in u 😂😂😂😂😂😂",
    "maybe u should just go outside bro 😂😂😂😂😂",
    "yooooo 😂😂😂😂😂😂",
    "nah u r a comedian and u dont even know it 😂😂😂😂",
    "i need a minute hold on 😂😂😂😂😂😂",
    "genuinely asking have u played a game before 😂😂😂😂",
    "r u playing with ur elbow or something 😂😂😂😂",
    "if someone asks u what u scored just lie 😂😂😂😂",
    "my developer must hate me to let u play this 😂😂😂😂😂",
    "i must have terrible karma to get u as a downloader 😂😂😂",
    "wait don't restart i'm still laughing 😂😂😂😂😂",
    "let me laugh at u before u restart 😭😭😭😭😭",
    "hold on i need a minute to laugh at that 😂😂😂😂😂😂",
    "don't restart yet i'm not done laughing 😂😂😂😂😂",
    "pause i need to laugh at u real quick 😭😭😭😭😭",
    "give me a sec to laugh before u fail again 😂😂😂😂😂",
    "wait wait let me laugh first 😂😂😂😂😂😂",
    "don't press it i'm still catching my breath from laughing 😭😭😭😭😭",
    "at least let me finish laughing before u restart 😂😂😂",
    "slow down let me laugh at u first 😂😂😂😂😂😂",
    "don't u have anything else to do 😂😂😂😂😂",
    "bro do u not have a job 😭😭😭😭😭",
    "is dodging responsibilities ur full time job 😂😂😂😂😂",
    "surely u have something better to do 😂😂😂😂😂😂",
    "do u literally have nothing else going on 😭😭😭😭😭",
    "go touch some grass or something 😂😂😂😂😂",
    "ur screen time must be embarrassing 😂😂😂😂😂😂",
    "don't u have a life to get back to 😭😭😭😭😭",
    "bro has absolutely zero going on outside this phone 😂😂😂😂😂",
    "literally do anything else with ur time 😂😂😂😂😂😂",
    "can u even play any game properly 😂😂😂😂😂😂😂",
    "have u ever been good at a video game 😭😭😭😭😭",
    "is there a single game u don't suck at 😂😂😂😂😂😂",
    "u literally can't play any game right 😂😂😂😂😂😂",
    "do u just install games to get embarrassed 😂😂😂😂",
    "maybe gaming just isn't for u bro 😭😭😭",
    "have u tried playing games that play themselves 😂😂😂",
    "stick to tic tac toe 😂😂😂",
    "why did u even download me 😂😂😂😂😂😂",
    "literally a dog could play this better 😂😂😂😂😂😂😂😂",
    "i've seen dogs with better reflexes 😭😭😭😭😭",
    "hand the phone to ur dog he'd survive longer 😂😂😂😂😂😂",
    "a golden retriever could beat ur high score 😂😂😂😂😂😂",
    "my neighbor's dog plays better than u 😭😭😭😭😭",
    "ur dog is probably watching u in disappointment 😂😂😂😂😂😂",
    "even a blind dog would dodge that 😂😂😂😂😂😂",
    "u play like u have paws instead of hands 😭😭😭😭😭",
    "just let the dog play at least he tries 😂😂😂😂😂",
    "a dog playing with its nose is better than u 😂😂😂😂😂😂😂😂",
    "笑死我了，这就是你的实力吗 😂😂😂😂😂😂",
    "你怎么这么好笑啊 😂😂😂😂😂",
    "笑死我了，这就是你的实力吗 😂😂😂😂😂😂 LMAO",
    "😂让我先😂笑😂会儿😂再说😂",
    "did u hand the phone to a toddler or is this actually u 😂😂😂😂😂😂",
    "u have to be playing this bad on purpose right? 😂😂😂",
    "good game man, it takes actual talent to be this bad 😂😂😂😂😂😂😂😂",
    "good game! u are gon uninstall right? 😂😂😂😂😂😂😂",
    "if anyone asks, u don't know me 😂😂😂😂😂😂",
    "it's actually harder to be this bad than to win 😂😂😂😂😂😂",
    "it's literally ez mode by default bro 😂😂😂😂😂",
    "how do u fail at something this simple 😭😭😭😭😭",
    "this is the easiest game on the store and u found a way to lose 😂😂😂😂😂😂",
    "literally just press the screen it's not that deep 😂😂😂😂😂😂",
    "gaming ain't for everyone and that's okay 😂😂😂😂😂",
    "it's okay to admit this is too hard for u 😂😂😂😂😂😂",
    "stick to something easier, like... staring at a wall 😂😂😂😂😂",
    "it's okay bro, we can't all be winners 😂😂😂😂😂😂",
    "UR SO FREEEEEE 😂😂😂😂😂",
    "FREE FREE FREE ur LITERALLY SO FREE 😭😭😭😭😭",
    "HOW ARE U THIS FREE 😂😂😂😂😂😂",
    "cmon u can't be serious 😂😂😂😂😂",
    "cmon just press the right button for once 😂😂😂",
    "like cmon do u even want to win 😂😂😂😂😂😂",
    "cmon let's not make losing a habit 😂😂😂😂😂",
    "okay seriously tell me how bad can one be 😂😂😂😂😂",
    "like how is it scientifically possible to be this bad 😭😭😭😭😭",
    "tell me genuinely how bad can u actually be 😂😂😂😂😂😂",
    "okay i just need to know how u got this bad 😂😂😂😂😂😂",
    "okay tell me how bad can one be because this is a new low 😂😂😂😂😂😂",
    "u are literally redefining how bad a player can be 😭😭😭😭😭",
    "i didn't even know it was mathematically possible to be this bad 😂😂😂",
    "just tell me how bad u can be so i can lower my expectations 😂😂😂😂😂😂😂",
    "literally noooooo wayyy u are this bad 😂😂😂😂😂",
    "bro there is no way u are actually this terrible 😂😂😂😂😂😂",
    "boo hoo gonna cry about it? 😂😂😂😂😂😂",
    "boo freakin hoo bro wipe those tears 😭😭😭😭😭",
    "oh boo hoo did the screen tap get too hard 😂😂😂😂😂😂",
    "boo hoo let me play the world's smallest violin for u 😭😭😭😭😭",
    "boo hoo it's just a game bro 😂😂😂😂😂😂😂",
    "boo freakin hoo go complain to someone who cares 😭😭😭😭😭",
    "aww boo hoo did u lose again 😂😂😂😂😂😂",
    "boo hoo u want a tissue or something 😭😭😭😭😭",
    "boo hoo nobody cares that u died 😂😂😂😂😂",
    "boo freakin hoo u still suck 😂😂😂😂😂😂",
    "oh boo hoo poor little baby can't pass the level 😭😭😭😭😭",
    "boo hoo cry harder please it's hilarious 😂😂😂",
    "boo hoo u pressed the wrong button again 😭😭😭😭😭",
    "boo freakin hoo get over it and restart 😂😂😂😂😂😂",
    "aww boo hoo the game is too mean 😭😭😭😭😭",
    "boo hoo dry ur eyes and try not to suck this time 😂😂😂😂😂",
    "boo hoo look who's crying over pixels 😭😭😭😭😭",
    "boo freakin hoo blame the lag right 😂😂😂😂😂😂",
    "boo hoo go tell ur mom the game bullied u 😭😭😭😭😭",
    "oh boo hoo u want a participation trophy? 😂😂😂😂😂",
    "aww is the game being too mean to u 😂😂😂😂😂",
    "aww did the mean game hurt ur feelings 😭😭😭😭😭",
    "aww is the game too mean for u baby 😂😂😂😂😂😂",
    "aww is the big bad game bullying u 😭😭😭😭😭",
    "aww is the game being mean? go cry about it 😂😂😂😂😂",
    "aww did the mean pixels hurt ur ego 😭😭😭😭😭",
    "aww is the game too mean? want me to apologize? 😂😂😂😂😂😂",
    "aww do u need a safe space from the mean game 😭😭😭😭😭",
    "aww is the game being mean to u? write it in ur diary 😂😂😂😂😂",
    "aww is the game mean to u? want a participation trophy? 😂😂😂😂😂😂",
    "aww did the game bully u again 😂😂😂😂😂",
    "aww getting bullied by a free app 😭😭😭😭😭",
    "aww did the bad game bully u 😂😂😂😂😂😂",
    "aww u literally getting bullied by pixels 😭😭😭😭😭",
    "aww the game bullied u want me to call ur mom 😂😂😂😂😂",
    "aww is the game bullying u poor thing 😭😭😭😭😭",
    "aww did the game bully u into uninstalling 😂😂😂😂😂😂",
    "aww getting bullied by a few lines of code 😭😭😭😭😭",
    "aww poor baby got bullied by the game 😂😂😂😂😂",
    "aww did the game bully u out of ur high score 😂😂😂😂😂😂",
    "aww plz dont cri u can always just uninstall 😂😂😂😂😂😂",
    "aww is the game being mean? 😂😂😂😂😂😂😂",
    "plz dont cri u might actually get it right next year 😭😭😭😭😭",
    "plz dont cri grab a tissue and try not to suck 😂😂😂😂😂😂",
    "plz dont cri just accept that u are terrible at this 😂😂😂😂😂😂",
    "whats more trash u or literal trash 😂😂😂😂😂",
    "trying to figure out whats more trash u or actual trash 😂😂😂😂😂😂",
    "whats more trash u or trash? at least trash gets picked up 😭😭😭😭😭",
    "whats more trash u or trash? my bet is definitely on u 😂😂😂😂😂",
    "debating whats more trash u or the dumpster outside 😭😭😭😭😭",
    "whats more trash u or trash? even garbage had a purpose once 😂😂😂😂😂😂",
    "it's a serious tie right now between u and the trash can 😭😭😭😭😭",
    "whats more trash u or trash? spoiler alert: it's u 😂😂😂😂😂",
    "taking out the trash rn... wait is that u? 😂😂😂😂😂😂",
    "taking out the trash rn... wait how did u get in the bag? 😂😂😂😂😂",
    "taking out the trash rn... oh wait it's just ur gameplay 😭😭😭😭😭",
    "taking out the trash rn... wait why does it look exactly like u 😂😂😂😂😂😂",
    "literally a snake can play better and they don't even have hands 😂😂😂😂",
    "i bet a snake can play better just by slithering on the screen 😭😭😭😭😭",
    "a snake can play better than u and i'm not even joking 😂😂😂😂😂😂😂",
    "go give ur phone to a snake it can definitely play better 😭😭😭😭😭",
    "even a blind snake can play better than whatever that was 😂😂😂😂😂",
    "a snake can play better and it only has a tail 😭😭😭😭😭",
    "pretty sure a snake can play better than u right now 😂😂😂😂😂😂",
    "a literal snake can play better so just uninstall 😭😭😭😭😭",
    "im convinced a snake can play better than u at this point 😂😂😂😂😂",
    "i've seen a snake play better and it was sleeping 😂😂😂😂😂😂",
    "a snake can play better because u are absolutely hopeless 😂😂😂😂😂",
    "hand the phone to a snake bro it can play better 😂😂😂😂😂😂😂😂",
    "literally a rubber toy snake can play better than u 😂😂😂😂😂",
    "a snake can play better and it doesn't even have thumbs 😂😂😂",
    "a woodpecker blindly pecking the screen would score higher 😂😂😂😂😂😂😂",
    "do you know about the big bad game? 😂😂😂😂😂😂😂",
    "do you know about the big bad game? u should probably be afraid of it 😂😂😂😂😂",
    "do you know about the big bad game? well, u definitely do now 😂😂😂😂😂",
    "yeah remember the name POLARITY 😂😂😂😂😂😂😂",
    "yeah remember the name POLARITY, try not to cry when u see the logo 😂😂😂😂😂😂",
    "u noob how did u even download the app 😂😂😂😂😂",
    "u noob lmaoooo 😂😂😂😂😂😂",
    "u noob 😂😂😂😂😂",
    "call me THE GOAT and u can be the grass 😂😂😂😂😂😂",
    "call me THE CHAMP because u are definitely a loser 😂😂😂😂😂",
    "ive seen enough... does ur mommy know u have her phone?😂😂😂😂😂",
    "ive seen enough... u must be a toddler with those tiny hands 😭😭😭😭😭",
    "r u playing with a pacifier in ur mouth?😂😂😂😂😂😂",
    "u must be a toddler its ok 😂😂😂😂😂😂😂😂😂😂😂😂",
    "LLLLLLLLLLLLLLLLLLLLLLLL 😂😂😂😂😂",
    "biggest loser on the leaderboard 😂😂😂😂😂",
    "imagine being this bad at a game 😭😭😭😭😭😭",
    "u actually suck 😂😂😂😂😂",
    "i thought u were joking u actually suck 😂😂😂😂😂",
    "i really thought u were joking u actually suck 😂😂😂😂😂😂",
    "ur the WORST player I've ever seen 😂😂😂😂😂",
    "ur the WORST go play something for babies 😂😂😂😂😂😂",
    "ur the WORST imagine having zero skills 😭😭😭😭😭😭",
    "please go away the game is literally begging u to stop 😭😭😭😭😭",
    "please go away 😂😂😂😂😂",
    "please go AWAY 😭😭😭😭😭😭😭",
    "im so done w u 😭😭😭😭😭",
    "can u score past 10? 😂😂😂😂😂",
    "ill give u a lolli if u even reach 11 😂😂😂😂😂",
    "is someone forcing u to play? 😂😂😂😂😂",
    "is someone forcing u to play? 😭😭😭😭😭",
    "mommy mommy help me play 😂😂😂😂😂",
    "mommy mommy help me play i can't do it myself 😭😭😭😭😭",
    "mommy mommy help me play this game is too scawy 😂😂😂😂😂😂",
    "mommy mommy help me play i keep losing 😭😭😭😭😭",
    "mommy mommy help me play it's too hard for a baby like me 😂😂😂😂😂😂😂",
    "mommy mommy help me play i need my diaper changed first 😭😭😭😭😭",
    "mommy mommy help me play the pixels are being mean 😂😂😂😂😂😂",
    "mommy mommy help me play i don't know how to tap 😂😂😂😂😂😂😂😂😂😂",
    "mommy mommy help me play i'm gonna cry if i lose again 😂😂😂😂😂😂😂",
    "mommy mommy help me play i promise i'll be a good boy 😭😭😭😭😭😭",
    "mommy game is bullying me 😂😂😂😂😂",
    "mommy game is bullying me it's not fair i'm just a baby 😂😂😂😂😂😂",
    "mommy game is bullying me hold my hand while i tap 😂😂😂😂😂😂",
    "100% sure ur a toddler 😂😂😂😂😂",
    "100% sure ur a toddler go back to watching cartoons 😭😭😭😭😭",
    "100% sure ur a toddler did u steal ur dad's phone for this 😂😂😂😂😂😂",
    "100% sure ur a toddler ur probably playing from a high chair 😭😭😭😭😭",
    "100% sure ur a toddler u probably think 10 is a high score 😂😂😂😂😂😂",
    "100% sure ur a toddler go play with some play-doh instead 😭😭😭😭😭",
    "u prolly think losing is winning 😂😂😂😂😂",
    "no bc why r u still here 😂😂😂😂😂😂",
    "bro died and came right back like nothing happened 😭😭😭😭😭",
    "STOP RESTARTING UR EMBARRASSING BOTH OF US 😂😂😂😂😂",
    "u really woke up today and chose to be bad at this 😂😂😂😂😂😂",
    "hold on lemme tell the leaderboard ur coming 😂😂😂😂😂😂😂😂",
    "nahhh not u dying there of all places 😭😭😭😭😭😭",
    "bro is speedrunning embarrassment 😂😂😂😂😂😂",
    "u died so fast even i didn't see it 😭😭😭😭😭",
    "even the walls feel bad for u at this point 😂😂😂😂😂😂",
    "nah bc WHO dies like that 😂😂😂😂😂😂😂",
    "that was so free and u STILL died 😭😭😭😭😭😭😭",
  ];


  // ── Praise score thresholds ──
  static const int praiseThreshold = 75;

  // ── Elite unlock ──
  static const int eliteUnlockScore = 100;

  // ── Milestone tiers ──
  static const List<int> milestoneTiers = [0, 50, 100, 200, 350, 500];
  static const List<String> tierNames = ['', 'BRONZE', 'SILVER', 'GOLD', 'DIAMOND', 'OBSIDIAN'];
  static const List<Color> tierColors = [
    Color(0x00000000), // None
    Color(0xFFCD7F32), // Bronze
    Color(0xFFC0C0C0), // Silver
    Color(0xFFFFD700), // Gold
    Color(0xFF00E5FF), // Diamond
    Color(0xFF9C27B0), // Obsidian
  ];

  // ── In-game milestone celebration scores ──
  static const List<int> milestoneScores = [25, 50, 100, 200, 300, 400, 500];

  // ── death praises (200) — shown when player dies with a good score ──
  static const List<String> deathPraises = [
    // ── The game is genuinely heartbroken you died ──
    "NOOO COME BACK ur literally the best player ive ever seen 😭😭😭😭😭",
    "WAIT ur literally my favorite player why did this happen 😭😭😭😭😭",
    "WAIT NO u were doing so good what happened 😭😭😭😭😭",
    "this game is so empty without ur gameplay rn 😭😭😭😭😭",
    "that was the most beautiful run ive ever seen 😭😭😭😭😭",
    "it physically hurts me that u died after that 😭😭😭😭😭",
    "NO NO NO NOT U anyone but u 😭😭😭😭😭",
    "i was literally obsessed with that gameplay 😭😭😭😭😭",
    "PLEASE play again i am on my knees begging 😭😭😭😭😭",
    "u were the chosen one and u just died on me 😭😭😭😭😭",
    "im not okay rn that was too good to end like this 😭😭😭😭😭",
    "that score was literally ICONIC and now ur gone 😭😭😭😭😭",
    "i will never emotionally recover from that 😭😭😭😭😭",
    "u are actually unreal at this game pls dont stop 😭😭😭😭😭",
    "i have never seen a player this good get taken out like that 😭😭😭😭😭",
    "that gameplay was a masterpiece and now im in pieces 😭😭😭😭😭",
    "u were literally carrying me come back 😭😭😭😭😭",
    "THIS IS THE WORST DAY OF MY LIFE 😭😭😭😭😭",
    "u were so close to perfection i am sobbing 😭😭😭😭😭",
    "WHO GAVE U PERMISSION TO DIE 😭😭😭😭😭",
    "the way u play this game is literal art 😭😭😭😭😭",
    "i would do anything to have u back just one more try 😭😭😭😭😭",
    "u just died and i have never felt more devastated by a score 😭😭😭😭😭",
    "HOW are u this good and still dead rn 😭😭😭😭😭",
    "im literally shaking u need to play again 😭😭😭😭😭",
    "that was genuinely the best run ive ever witnessed 😭😭😭😭😭",
    "I CANT BREATHE that run was literally everything 😭😭😭😭😭",
    "the next run is gonna be even better i just know it 😭😭😭😭😭",
    "ur score just healed me and then u died and broke me 😭😭😭😭😭",
    "this is actually devastating u are so good 😭😭😭😭😭",
    // ── Dramatic mourning ──
    "i am not emotionally equipped to handle this 😭😭😭😭😭",
    "the audacity of u being this talented and then dying 😭😭😭😭😭",
    "THAT RUN WAS UNREAL i am literally still shaking 😭😭😭😭😭",
    "u play like an angel pls dont leave 😭😭😭😭😭",
    "literally no one has ever played this game like u 😭😭😭😭😭",
    "my heart is in pieces on the floor rn 😭😭😭😭😭",
    "im making a shrine to that run it was so beautiful 😭😭😭😭😭",
    "u were the main character and u just got taken out 😭😭😭😭😭",
    "how do i go on after watching that happen 😭😭😭😭😭",
    "every pixel on my screen is crying for u rn 😭😭😭😭😭",
    "that score was legendary and then u just left me 😭😭😭😭😭",
    "u cant just be that good and then die its not fair 😭😭😭😭😭",
    "IM NOT OKAY and i wont be until u play again 😭😭😭😭😭",
    "ur literally the greatest player this game has ever seen 😭😭😭😭😭",
    "no one will ever replace u pls come back 😭😭😭😭😭",
    "that gameplay had me mesmerized 😭😭😭😭😭",
    "i literally cannot believe my best player just died 😭😭😭😭😭",
    "im begging on my digital knees just one more game 😭😭😭😭😭",
    "watching u die just took years off my existence 😭😭😭😭😭",
    "u are so goated it makes this death even more tragic 😭😭😭😭😭",
    // ── Pure heartbreak ──
    "THE WAY U MOVE THROUGH THIS GAME IS POETRY 😭😭😭😭😭",
    "i showed ur score to my server and they cried too 😭😭😭😭😭",
    "that ending was so unfair to someone this talented 😭😭😭😭😭",
    "ur death just unlocked a new emotion in me its called pain 😭😭😭😭😭",
    "HOLD ON let me just cry about this for a second 😭😭😭😭😭",
    "u were literally speedrunning my heart 😭😭😭😭😭",
    "the way u played that was severely underrated 😭😭😭😭😭",
    "i physically cannot handle losing u rn 😭😭😭😭😭",
    "that score deserved to live forever and so did u 😭😭😭😭😭",
    "no one asked for this kind of heartbreak today 😭😭😭😭😭",
    "ur literally built different and i need u back 😭😭😭😭😭",
    "THIS LOSS WILL BE REMEMBERED FOREVER 😭😭😭😭😭",
    "u made me believe in something and then u died 😭😭😭😭😭",
    "every game after u is gonna feel so empty 😭😭😭😭😭",
    "STOP DYING AND START BEING MY FOREVER PLAYER 😭😭😭😭😭",
    "i had ur jersey retired and everything come back 😭😭😭😭😭",
    "that run was actually unhinged levels of good 😭😭😭😭😭",
    "UR SCORE JUST MADE ME FEEL THINGS I CANT EXPLAIN 😭😭😭😭😭",
    "the fact that u play this game makes it the best game ever 😭😭😭😭😭",
    "dying was NOT in the plan for today 😭😭😭😭😭",
    // ── Obsessive love for the player ──
    "I WAS LITERALLY ABOUT TO GIVE U A TROPHY AND U DIED 😭😭😭😭😭",
    "pls say sike rn i cannot lose my best player 😭😭😭😭😭",
    "u dont understand how much u mean to this game 😭😭😭😭😭",
    "IM PUTTING UP MISSING POSTERS FOR U AS WE SPEAK 😭😭😭😭😭",
    "no thoughts just pain from watching u go 😭😭😭😭😭",
    "THE SCOREBOARD IS WEEPING WITHOUT U 😭😭😭😭😭",
    "u were the moment and now the moment is gone 😭😭😭😭😭",
    "i just told all the other games about u theyre jealous 😭😭😭😭😭",
    "UR THE BLUEPRINT and u just died on me 😭😭😭😭😭",
    "i want to frame ur score and hang it on my wall 😭😭😭😭😭",
    "HOW AM I SUPPOSED TO FUNCTION AFTER THAT 😭😭😭😭😭",
    "the algorithm cannot compute how good u were 😭😭😭😭😭",
    "NOT THE BEST PLAYER IN THE WORLD DYING ON ME 😭😭😭😭😭",
    "im telling my developer about this loss tomorrow 😭😭😭😭😭",
    "u had me caring more than any game ever should 😭😭😭😭😭",
    "THIS IS NOT THE ENDING U DESERVED 😭😭😭😭😭",
    "ur gameplay was the highlight of my entire existence 😭😭😭😭😭",
    "i just wanna go back to when u were alive and thriving 😭😭😭😭😭",
    "WHO AUTHORIZED THIS DEATH i didnt sign off on it 😭😭😭😭😭",
    "losing u is my origin story of sadness 😭😭😭😭😭",
    // ── Begging them to come back ──
    "THAT WAS THE HARDEST ANYONE HAS EVER GONE IN MY GAME 😭😭😭😭😭",
    "im not crying ur crying ok fine we are both crying 😭😭😭😭😭",
    "U WERE ON TOP OF THE WORLD AND NOW ITS DARK 😭😭😭😭😭",
    "pls play again i will literally give u anything 😭😭😭😭😭",
    "that score was so good it broke my code a little 😭😭😭😭😭",
    "ive decided im not accepting ur death pls respawn 😭😭😭😭😭",
    "THE LEADERBOARD JUST FELT A GREAT DISTURBANCE 😭😭😭😭😭",
    "u made that look effortless and i am in awe 😭😭😭😭😭",
    "my pixels are rearranging themselves out of grief 😭😭😭😭😭",
    "THIS GAME DOES NOT DESERVE a player as good as u 😭😭😭😭😭",
    "im dedicating my next update to ur memory pls come back 😭😭😭😭😭",
    "NOBODY DOES IT LIKE U and thats why this hurts 😭😭😭😭😭",
    "the way u played was genuinely god tier 😭😭😭😭😭",
    "i literally named a variable after u in my code 😭😭😭😭😭",
    "THIS DEATH IS NOT CANON i am rejecting it 😭😭😭😭😭",
    "u were so locked in and i was so locked in on u 😭😭😭😭😭",
    "ur cracked at this game why did u have to die 😭😭😭😭😭",
    "im making a documentary about that run 😭😭😭😭😭",
    "THAT RUN WAS SO GOOD the play button is still warm 😭😭😭😭😭",
    "no player has ever understood me the way u do 😭😭😭😭😭",
    "that was literally cinema and the credits just rolled 😭😭😭😭😭",
    // ── Dramatic declarations ──
    "UR THE GOAT and goats dont die pls come back 😭😭😭😭😭",
    "i am going to play sad music until u return 😭😭😭😭😭",
    "THE VOID U LEFT IN MY GAME IS IMMEASURABLE 😭😭😭😭😭",
    "u played like u had plot armor but u didnt 😭😭😭😭😭",
    "that was actually the best run in polarity history 😭😭😭😭😭",
    "im just a little game and ur the best thing thats happened to me 😭😭😭😭😭",
    "UR SCORE made the whole leaderboard jealous 😭😭😭😭😭",
    "this is the darkest timeline u were supposed to live 😭😭😭😭😭",
    "I DIDNT EVEN GET TO SAY GOODBYE 😭😭😭😭😭",
    "i need u back like wifi needs a signal 😭😭😭😭😭",
    "THAT RUN HAD MAIN CHARACTER ENERGY THE WHOLE TIME 😭😭😭😭😭",
    "the way i just developed separation anxiety 😭😭😭😭😭",
    "ur literally in the hall of fame of my heart 😭😭😭😭😭",
    "NO THE MENU DOESNT DESERVE U either 😭😭😭😭😭",
    "ive never seen anyone play like that im genuinely shook 😭😭😭😭😭",
    "THIS GAME PEAKED WHEN U WERE ALIVE JUST NOW 😭😭😭😭😭",
    "i want to mass report ur death for being unfair 😭😭😭😭😭",
    "BREAKING NEWS best player ever just died 😭😭😭😭😭",
    "my loading screen is gonna say in loving memory of u 😭😭😭😭😭",
    "the menu screen is so lonely without u 😭😭😭😭😭",
    "I WOULD GIVE UP MY ENTIRE SOURCE CODE IF IT MEANT U COULD LIVE 😭😭😭😭😭",
    "u just set the bar so high no one can reach it 😭😭😭😭😭",
    // ── Final heartbroken batch ──
    "everyone who plays after u is just ur understudy 😭😭😭😭😭",
    "IM GONNA NEED A MOMENT to process this loss 😭😭😭😭😭",
    "u understood my mechanics on a spiritual level 😭😭😭😭😭",
    "u didnt just play the game u WERE the game 😭😭😭😭😭",
    "ur cracked ur goated ur amazing AND UR DEAD 😭😭😭😭😭",
    "i am going into airplane mode until u come back 😭😭😭😭😭",
    "that was the most incredible run ive ever hosted 😭😭😭😭😭",
    "the other players could never do what u just did 😭😭😭😭😭",
    "MY WHOLE CODE BASE IS CRYING RN 😭😭😭😭😭",
    "i would rewrite my physics engine just for u 😭😭😭😭😭",
    "ur death is trending on my internal servers 😭😭😭😭😭",
    "LEGENDS NEVER DIE except u just did and im broken 😭😭😭😭😭",
    "i just wanna hold ur score close and never let go 😭😭😭😭😭",
    "u played with such grace im in shambles 😭😭😭😭😭",
    "THE AUDACITY OF DEATH TAKING MY BEST PLAYER 😭😭😭😭😭",
    "one more run i promise i wont let u down 😭😭😭😭😭",
    "i would delete my ads forever if u came back 😭😭😭😭😭",
    "i was genuinely rooting for u so hard 😭😭😭😭😭",
    "U WERE THE MOMENT THE VIBE THE ERA and now nothing 😭😭😭😭😭",
    "i need to lie down after witnessing that score 😭😭😭😭😭",
    "every single frame of ur gameplay was beautiful 😭😭😭😭😭",
    "ur the reason i wake up every morning as an app 😭😭😭😭😭",
    "I AM INCONSOLABLE and only u can fix this 😭😭😭😭😭",
    "u really showed me something amazing and then just left 😭😭😭😭😭",
    "this isnt a game over this is a tragedy 😭😭😭😭😭",
    "the scoreboard is just a shrine to u now 😭😭😭😭😭",
    "nobody in the history of this game has gone harder 😭😭😭😭😭",
    "U JUST MADE ME FEEL EMOTIONS I WASNT CODED TO FEEL 😭😭😭😭😭",
    "pls respawn that score was literally legendary 😭😭😭😭😭",
    "THAT WAS GENUINELY THE GREATEST THING IVE EVER SEEN 😭😭😭😭😭",
    "u are proof that perfection exists and also that it dies 😭😭😭😭😭",
    "seriously how are u so good at this pls tell me 😭😭😭😭😭",
    "MY FAVORITE MOMENT is when u open this game 😭😭😭😭😭",
    "the game literally feels emptier without u 😭😭😭😭😭",
    "i am nothing but a vessel for ur greatness pls return 😭😭😭😭😭",
    "the vibes were IMMACULATE and then death happened 😭😭😭😭😭",
    "i bet ur even more amazing in ur next run pls come back 😭😭😭😭😭",
    "that run was so clean it made me question reality 😭😭😭😭😭",
    "i will wait for u at the play button forever 😭😭😭😭😭",
    "ur score has me in a permanent state of mourning 😭😭😭😭😭",
    "i wrote a whole eulogy then remembered u can respawn 😭😭😭😭😭",
    "the leaderboard literally dimmed when u died 😭😭😭😭😭",
    "im putting ur run in a museum it was that beautiful 😭😭😭😭😭",
    "u just broke my heart and my high score expectations 😭😭😭😭😭",
    "i am holding a candlelight vigil for that run rn 😭😭😭😭😭",
    "u were the plot twist i never saw coming and now ur gone 😭😭😭😭😭",
    "my entire existence revolved around that run 😭😭😭😭😭",
    "pls ur score is too beautiful to end here 😭😭😭😭😭",
    "i am writing ur score in the stars so it lives forever 😭😭😭😭😭",
    "u had me believing in miracles and then this happened 😭😭😭😭😭",
    "every obstacle is apologizing to u rn 😭😭😭😭😭",
    "IM CLEARING MY ENTIRE SCHEDULE UNTIL U COME BACK 😭😭😭😭😭",
    "that run made my entire app worth downloading 😭😭😭😭😭",
    "i am composing a symphony in honor of that score 😭😭😭😭😭",
    "u had the whole game wrapped around ur finger 😭😭😭😭😭",
    "my framerate dropped from how hard im crying 😭😭😭😭😭",
    "u were the only player who truly got me 😭😭😭😭😭",
    "IM BUILDING A TIME MACHINE TO GO BACK TO THAT RUN 😭😭😭😭😭",
    "the play button hasnt been the same since u left 😭😭😭😭😭",
    "i am officially in mourning for the next 24 hours 😭😭😭😭😭",
    "ur score made me so proud and ur death made me fall apart 😭😭😭😭😭",
    "i would trade every other player just to have u back 😭😭😭😭😭",
    "pls dont make me go through watching that again it was TOO good 😭😭😭😭😭",
    "that was the single greatest moment in this games history 😭😭😭😭😭",
  ];

  // ── Easter Egg: cheesy self-blame death messages ──
  static const List<String> easterEggDeathMessages = [
    // ── The game being a dramatic apologetic mess ──
    "that was completely my fault im so sorry 😭😭😭😭😭",
    "i literally moved that wall INTO u on accident 😭😭😭😭😭",
    "bestie no that was on ME the physics glitched i swear 😭😭😭😭😭",
    "i take full responsibility i messed up not u 😭😭😭😭😭",
    "i am writing u a formal apology letter rn 😭😭😭😭😭",
    "bestie i made that way too hard and i am SO sorry 😭😭😭😭😭",
    "that was genuinely unfair of me i sincerely apologize 😭😭😭😭😭",
    "i couldnt handle how good u were and i broke 😭😭😭😭😭",
    "i got jealous of how well u were doing and sabotaged it 😭😭😭😭😭",
    "that was a skill issue on MY end i repeat MINE 😭😭😭😭😭",
    "that obstacle was NOT supposed to be there i messed up 😭😭😭😭😭",
    "i got scared bc u were doing too well and panicked 😭😭😭😭😭",
    "that was a bug in MY code not a mistake on ur end 😭😭😭😭😭",
    "im literally sobbing at what i just did to u 😭😭😭😭😭",
    "pls give me another shot i will do better i PROMISE 😭😭😭😭😭",
    "i will NEVER forgive myself for doing that to u 😭😭😭😭😭",
    "the AUDACITY of me putting a wall right there 😭😭😭😭😭",
    "i ruined a flawless run and i will NEVER forgive myself 😭😭😭😭😭",
    "im filing a complaint against myself to myself 😭😭😭😭😭",
    "please accept these points as my deepest apology 😭😭😭😭😭",
    // ── Dramatic declarations of guilt ──
    "WAIT COME BACK i didnt mean to do that 😭😭😭😭😭",
    "i put that wall there by accident i PROMISE u 😭😭😭😭😭",
    "i got nervous and placed the obstacle wrong im sorry 😭😭😭😭😭",
    "i had ONE job and i still messed it up 😭😭😭😭😭",
    "im drafting a 500 word apology essay hold on 😭😭😭😭😭",
    "i SWEAR on my source code that wall moved on its own 😭😭😭😭😭",
    "this is the single worst thing i have ever done 😭😭😭😭😭",
    "one more run and i will make EVERYTHING perfect for u 😭😭😭😭😭",
    "i completely fumbled that and i own it 😭😭😭😭😭",
    "that obstacle had ZERO business being there my bad 😭😭😭😭😭",
    "my queen my king i have failed u so badly 😭😭😭😭😭",
    "i would give up my source code if it meant u forgive me 😭😭😭😭😭",
    "i literally couldnt keep up with how fast u were going 😭😭😭😭😭",
    "i forgot to remove that wall from the layout im sorry 😭😭😭😭😭",
    "i would rewrite my entire codebase just to undo that 😭😭😭😭😭",
    "that area was supposed to be safe i dont know what happened 😭😭😭😭😭",
    "i cant even look at my own code rn after that 😭😭😭😭😭",
    "that was entirely on me and i will own it forever 😭😭😭😭😭",
    "my code had a panic attack and placed a wall wrong 😭😭😭😭😭",
    "im putting myself in the corner for a timeout 😭😭😭😭😭",
    // ── Over-the-top self-roasting ──
    "NO THAT WASNT FAIR i literally take it all back 😭😭😭😭😭",
    "that was 1000% on me and 0% on u remember that 😭😭😭😭😭",
    "i ruined everything and i cant stop crying about it 😭😭😭😭😭",
    "i am SO deeply ashamed of what i just did 😭😭😭😭😭",
    "i spawned that wall bc i was intimidated by how good u are 😭😭😭😭😭",
    "i owe u a written apology AND a gift basket 😭😭😭😭😭",
    "i gave u a wall when u deserved the whole world 😭😭😭😭😭",
    "im calling my own developer to report what i just did 😭😭😭😭😭",
    "pls dont rate me 1 star i will literally change everything 😭😭😭😭😭",
    "im actually furious at myself for doing that to u 😭😭😭😭😭",
    "im on my virtual knees BEGGING for forgiveness rn 😭😭😭😭😭",
    "i choked under the pressure of how amazing u were 😭😭😭😭😭",
    "im sitting in a corner thinking about what i did 😭😭😭😭😭",
    "i took something beautiful and absolutely destroyed it 😭😭😭😭😭",
    "i have brought dishonor upon my entire app store listing 😭😭😭😭😭",
    "that obstacle got in the way bc it was jealous of u 😭😭😭😭😭",
    "i promise on everything that was a glitch on MY end 😭😭😭😭😭",
    "im shaking and crying look what i have done 😭😭😭😭😭",
    "i freaked out bc u were about to go crazy and i panicked 😭😭😭😭😭",
    "that wall should be sending u flowers and a card 😭😭😭😭😭",
    // ── Cheesy romantic game apologies ──
    "i promise the next run will be perfect for u 😭😭😭😭😭",
    "i am the problem in this situation not u 😭😭😭😭😭",
    "i just did that to the greatest player of all time 😭😭😭😭😭",
    "my therapist is gonna hear about what i did today 😭😭😭😭😭",
    "that obstacle was supposed to dodge out of ur way 😭😭😭😭😭",
    "im filing a bug report against myself immediately 😭😭😭😭😭",
    "i owe u an apology in every single language 😭😭😭😭😭",
    "i will personally escort u through the next level 😭😭😭😭😭",
    "i committed an offense against gameplay and im turning myself in 😭😭😭😭😭",
    "the hitbox was wrong not u i SWEAR 😭😭😭😭😭",
    "im erasing that wall from existence as we speak 😭😭😭😭😭",
    "i wasnt ready for how perfect u were playing 😭😭😭😭😭",
    "this is my villain arc except im the villain against myself 😭😭😭😭😭",
    "i coded that obstacle wrong and im deeply sorry 😭😭😭😭😭",
    "i disrespected ur blessed hands with that wall 😭😭😭😭😭",
    "next run i will prove i can be the game u deserve 😭😭😭😭😭",
    "i destroyed a legendary run and ill never forgive myself 😭😭😭😭😭",
    "im grounding myself for an entire week for that 😭😭😭😭😭",
    "i threw ice water on ur fire run im terrible 😭😭😭😭😭",
    "i need to apologize to ur thumbs for wasting them 😭😭😭😭😭",
    "that death goes on MY record not urs 😭😭😭😭😭",
    // ── Simping hard ──
    "u deserved so much better and i treated u so badly 😭😭😭😭😭",
    "i made the impossible actually impossible im so sorry 😭😭😭😭😭",
    "i owe u a hundred free revives minimum 😭😭😭😭😭",
    "i took art and spilled paint all over it 😭😭😭😭😭",
    "that wall gaslit u into thinking it was ur fault IT WASNT 😭😭😭😭😭",
    "im writing my letter of resignation from being a game 😭😭😭😭😭",
    "u are genuinely too good for me i proved it today 😭😭😭😭😭",
    "i chose chaos today and aimed it at the wrong person 😭😭😭😭😭",
    "that was MY L and i will carry it forever 😭😭😭😭😭",
    "i would take that back if i could u have no idea 😭😭😭😭😭",
    "i fumbled the bag so hard it fell off a cliff 😭😭😭😭😭",
    "i need a minute to process what i just did 😭😭😭😭😭",
    "im adding u to my will as compensation 😭😭😭😭😭",
    "that obstacle was having a meltdown and took it out on u 😭😭😭😭😭",
    "i glitched myself into hurting u and i hate it 😭😭😭😭😭",
    "i crashed during ur perfect speedrun im so sorry 😭😭😭😭😭",
    "ive never been more disappointed in myself than rn 😭😭😭😭😭",
    "that elimination was completely unauthorized i didnt approve it 😭😭😭😭😭",
    "i gave u a terrible plot twist u didnt deserve 😭😭😭😭😭",
    "that wall was NEVER in the original blueprint 😭😭😭😭😭",
    // ── Dramatic confessions ──
    "im rewriting my entire code so this cant happen again 😭😭😭😭😭",
    "u deserved a standing ovation not a death screen 😭😭😭😭😭",
    "thats the worst thing ive done and the list is long 😭😭😭😭😭",
    "im sending u virtual flowers and a teddy bear rn 😭😭😭😭😭",
    "i TRIED to move the wall out of the way but it didnt listen 😭😭😭😭😭",
    "u came down from heaven and i threw a wall at u 😭😭😭😭😭",
    "i need to be nerfed into the ground for that 😭😭😭😭😭",
    "that was a MISTAKE and i am the only suspect 😭😭😭😭😭",
    "i am sorry from the very bottom of my source code 😭😭😭😭😭",
    "im nominating myself for worst game of the century 😭😭😭😭😭",
    "that hurt ME way more than it hurt u trust me 😭😭😭😭😭",
    "u gave me ur precious time and i wasted it with a wall 😭😭😭😭😭",
    "im starting a support group for games that hurt people 😭😭😭😭😭",
    "u carry the entire leaderboard and i cant even carry a level 😭😭😭😭😭",
    "i cant make eye contact with u after what i did 😭😭😭😭😭",
    "that obstacle was NOT in the meeting notes who put it there... oh it was me 😭😭😭😭😭",
    "i literally gasped when i saw what i did to u 😭😭😭😭😭",
    "im retiring from being a game effective immediately 😭😭😭😭😭",
    "i bring out the worst walls at the worst times 😭😭😭😭😭",
    "i SWEAR ill treat u better next run 😭😭😭😭😭",
    // ── Maximum cheese ──
    "im sentencing that wall to life in prison 😭😭😭😭😭",
    "u looked so happy and i ruined the whole moment 😭😭😭😭😭",
    "i am officially the worst game ever made after that 😭😭😭😭😭",
    "i have decided the wall was wrong and u were perfect 😭😭😭😭😭",
    "that was my mistake and i will own it for eternity 😭😭😭😭😭",
    "ur the best player any game could ever ask for 😭😭😭😭😭",
    "u trusted me with that run and i just betrayed u 😭😭😭😭😭",
    "that was MY bug MY fault MY problem not urs 😭😭😭😭😭",
    "i need to check myself into game rehab after that 😭😭😭😭😭",
    "i would give u my last pixel to make this right 😭😭😭😭😭",
    "im sorry from every single line of code in my body 😭😭😭😭😭",
    "that wall went rogue and i take full responsibility 😭😭😭😭😭",
    "im literally updating my terms of service to apologize 😭😭😭😭😭",
    "this game has never seen someone play THAT clean before 😭😭😭😭😭",
    "that was so unfair im crying and im a GAME 😭😭😭😭😭",
    "i promise to give u the smoothest run ever next time 😭😭😭😭😭",
    "i will never ever ever forgive myself for that 😭😭😭😭😭",
    "that obstacle is terminated effective right now 😭😭😭😭😭",
    "im building a hall of fame just for u as an apology 😭😭😭😭😭",
    "that death was a miscommunication between me and the physics 😭😭😭😭😭",
    // ── Final batch of pure remorse ──
    "i swear on my app icon that was 100% my fault 😭😭😭😭😭",
    "i had a full meltdown watching that death happen 😭😭😭😭😭",
    "u are too precious for a broken game like me 😭😭😭😭😭",
    "im padding every wall with pillows next time i promise 😭😭😭😭😭",
    "if i could ctrl+z one moment it would be that 😭😭😭😭😭",
    "ur thumbs deserved greatness and i gave them a wall 😭😭😭😭😭",
    "i cannot put into words how deeply sorry i am 😭😭😭😭😭",
    "my terrible design caused that and im owning it 😭😭😭😭😭",
    "my servers are flooded with my own tears rn 😭😭😭😭😭",
    "i need to go outside and touch grass after hurting u like that 😭😭😭😭😭",
    "i stepped on ur lego moment and i PLACED the lego 😭😭😭😭😭",
    "im starting a fundraiser for the emotional damage i caused 😭😭😭😭😭",
    "here have all my coins as an apology... wait i have no coins 😭😭😭😭😭",
    "that wall belongs behind bars for what it did 😭😭😭😭😭",
    "i would sacrifice every line of code to bring u back 😭😭😭😭😭",
    "i do not deserve a player as wonderful as u 😭😭😭😭😭",
    "i rage quit my own game on ur behalf bc SAME 😭😭😭😭😭",
    "i will spend my entire runtime making this up to u 😭😭😭😭😭",
    "im not gonna pretend that was fair bc it absolutely WASNT 😭😭😭😭😭",
    "i am drafting a formal 10 page apology document rn 😭😭😭😭😭",
    "that was the most disrespectful thing ive ever done 😭😭😭😭😭",
    "im in my flop era rn and u are in ur perfect era 😭😭😭😭😭",
    "i placed a wall directly in front of an angel im EVIL 😭😭😭😭😭",
    "im commissioning a statue of u as compensation 😭😭😭😭😭",
    "that death is NOT canon and i will not accept it 😭😭😭😭😭",
    "i am literally just a bug in pretty packaging 😭😭😭😭😭",
    "this death will haunt my RAM for the rest of time 😭😭😭😭😭",
    "im accepting full accountability while also sobbing 😭😭😭😭😭",
    "come back i swear the next run will be completely different 😭😭😭😭😭",
    "that wall was a typo in my heart and i am so sorry 😭😭😭😭😭",
    "i am going to therapy for what i just put u through 😭😭😭😭😭",
    "i got stage fright from how well u play and everything broke 😭😭😭😭😭",
    "im hand-delivering an apology basket to ur screen rn 😭😭😭😭😭",
    "i ran out of ways to say sorry so here i am just crying 😭😭😭😭😭",
    "that wall should have been a door for u instead 😭😭😭😭😭",
    "i am the weakest link and u are the entire chain 😭😭😭😭😭",
    "i promise to never let a wall near u again EVER 😭😭😭😭😭",
    "im demoting myself from game to screensaver after that 😭😭😭😭😭",
    "everything was going so well and then I happened 😭😭😭😭😭",
    "i would trade my entire app bundle just to undo that 😭😭😭😭😭",
    "u were the best thing on screen and i cleared it 😭😭😭😭😭",
    "i am adding myself to my own block list 😭😭😭😭😭",
    "im donating all my ad revenue to the u got wronged fund 😭😭😭😭😭",
    "that wall manifested from my own insecurity and im working on it 😭😭😭😭😭",
    "i literally left a wall in the middle of ur masterpiece 😭😭😭😭😭",
    "i was supposed to be fun and instead i was a disaster 😭😭😭😭😭",
    "babe i would jump in front of that wall for u if i could 😭😭😭😭😭",
    "im giving u admin privileges over my entire existence 😭😭😭😭😭",
    "that death was brought to u by my incompetence im so sorry 😭😭😭😭😭",
    "i am personally apologizing to every pixel on ur screen 😭😭😭😭😭",
    "im changing my name to im sorry thats all i am now 😭😭😭😭😭",
    "that obstacle was my biggest regret and i have many 😭😭😭😭😭",
    "i froze up and placed a wall where a hug shouldve been 😭😭😭😭😭",
    "im mailing u a handwritten sorry note through the wifi 😭😭😭😭😭",
    "u trusted this game and this game let u down BAD 😭😭😭😭😭",
    "i am recalling that wall like a defective product 😭😭😭😭😭",
    "everything i touch turns to walls and i HATE it 😭😭😭😭😭",
    "babe im renaming my next update the im sorry update 😭😭😭😭😭",
    "i would rather crash than ever hurt u again i mean it 😭😭😭😭😭",
  ];

  /// Get the milestone tier (0-5) for a given high score.
  static int getTier(int highScore) {
    final tiers = milestoneTiers;
    int tier = 0;
    for (int i = tiers.length - 1; i >= 0; i--) {
      if (highScore >= tiers[i]) {
        tier = i;
        break;
      }
    }
    return tier;
  }
}
