import 'package:flutter/material.dart';

import 'visual_theme.dart';

class ThemeRegistry {
  ThemeRegistry._();

  static const List<List<VisualTheme>> themes = [
    [], // tier 0: classic (no themes)
    _tier1, // Awakening
    _tier2, // Ascension
    _tier3, // Mastery
    _tier4, // Legendary
    _tier5, // Transcendence
  ];

  static VisualTheme? selectTheme(int score, Map<int, int> rotationIndices) {
    final tier = _scoreToTier(score);
    if (tier == 0) return null;
    // V5: DFA compositing for post-500 scores (every 50 points past 500)
    if (score >= 550) return _dfaGenerate(score, rotationIndices);
    final variations = themes[tier];
    final idx = (rotationIndices[tier] ?? 0) % variations.length;
    return variations[idx];
  }

  static int scoreToTier(int score) => _scoreToTier(score);

  static int _scoreToTier(int score) {
    if (score >= 500) return 5;
    if (score >= 400) return 4;
    if (score >= 300) return 3;
    if (score >= 200) return 2;
    if (score >= 100) return 1;
    return 0;
  }

  static int advanceRotation(int tier, int currentIndex) {
    if (tier < 1 || tier > 5) return 0;
    return (currentIndex + 1) % themes[tier].length;
  }

  /// Restore a theme from persisted tier, variation, and score.
  /// For tiers 1-5, directly indexes the registry.
  /// For DFA (tier 6+), regenerates from the score.
  static VisualTheme? restoreTheme(int tier, int variation, int score,
      Map<int, int> rotationIndices) {
    if (tier <= 0) return null;
    if (tier <= 5) {
      final variations = themes[tier];
      if (variation < 0 || variation >= variations.length) return variations[0];
      return variations[variation];
    }
    // DFA theme: reconstruct from score
    if (score >= 550) return _dfaGenerate(score, rotationIndices);
    return null;
  }

  static VisualTheme _dfaGenerate(int score, Map<int, int> rotationIndices) {
    // DFA compositing: deterministic combination of existing themes
    final seed = score ~/ 50;
    final ballTier = ((seed * 7 + 3) % 5) + 1;
    final ballVar = ((seed * 13 + 5) % 10);
    final trailTier = ((seed * 11 + 7) % 5) + 1;
    final trailVar = ((seed * 17 + 11) % 10);
    final explosionTier = ((seed * 19 + 13) % 5) + 1;
    final explosionVar = ((seed * 23 + 17) % 10);

    final ballSrc = themes[ballTier][ballVar];
    final trailSrc = themes[trailTier][trailVar];
    final expSrc = themes[explosionTier][explosionVar];

    return ballSrc.copyWith(
      id: 'dfa_$seed',
      displayName: 'Beyond ${500 + (seed - 10) * 50}',
      tier: 6,
      variation: seed % 10,
      trailStyle: trailSrc.trailStyle,
      trailColors: trailSrc.trailColors,
      trailWidth: trailSrc.trailWidth,
      trailLife: trailSrc.trailLife,
      trailDensity: trailSrc.trailDensity,
      explosionPattern: expSrc.explosionPattern,
      explosionColors: expSrc.explosionColors,
      explosionParticleCount: expSrc.explosionParticleCount,
      explosionLife: expSrc.explosionLife,
      explosionGravity: expSrc.explosionGravity,
      magnetStyle: trailSrc.magnetStyle,
      magnetColors: trailSrc.magnetColors,
      wallStyle: expSrc.wallStyle,
      wallAccentColor: expSrc.wallAccentColor,
      wallGlowIntensity: expSrc.wallGlowIntensity,
    );
  }

  // ---------------------------------------------------------------------------
  // Tier 1 — "Awakening" (Score 100)
  // ---------------------------------------------------------------------------
  static const _tier1 = <VisualTheme>[
    // 1. Neon Pulse
    VisualTheme(
      id: 't1_neon_pulse',
      displayName: 'Neon Pulse',
      tier: 1,
      variation: 0,
      ballShape: BallShape.circle,
      ballColors: [Color(0xFF00FFFF), Color(0xFFFFFFFF)],
      ballGlowRadius: 10.0,
      ballGlowIntensity: 0.35,
      ballEffect: BallEffect.pulse,
      ballEffectSpeed: 1.2,
      trailStyle: TrailStyle.streaks,
      trailColors: [Color(0xFF00FFFF), Color(0xFF0088FF)],
      trailWidth: 1.2,
      trailLife: 1.1,
      trailDensity: 2,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFF00FFFF), Color(0xFF0044AA)],
      obstacleGlowIntensity: 0.4,
      explosionPattern: ExplosionPattern.ring,
      explosionColors: [Color(0xFF00FFFF), Color(0xFFFFFFFF)],
      explosionParticleCount: 120,
      explosionLife: 1.3,
      explosionGravity: 60.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFF00FFFF)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFF00FFFF)],
      ambientCount: 30,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFF00FFFF),
      wallGlowIntensity: 0.3,
    ),

    // 2. Crimson Flow
    VisualTheme(
      id: 't1_crimson_flow',
      displayName: 'Crimson Flow',
      tier: 1,
      variation: 1,
      ballShape: BallShape.hexagon,
      ballColors: [Color(0xFF8B0000), Color(0xFFCC1100)],
      ballGlowRadius: 8.0,
      ballGlowIntensity: 0.30,
      ballEffect: BallEffect.breathe,
      ballEffectSpeed: 0.9,
      trailStyle: TrailStyle.flames,
      trailColors: [Color(0xFFCC1100), Color(0xFF660000)],
      trailWidth: 1.4,
      trailLife: 1.0,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.flame,
      obstacleColors: [Color(0xFF8B0000), Color(0xFF440000)],
      obstacleGlowIntensity: 0.35,
      explosionPattern: ExplosionPattern.burst,
      explosionColors: [Color(0xFFCC1100), Color(0xFFFF4400), Color(0xFF660000)],
      explosionParticleCount: 100,
      explosionLife: 1.1,
      explosionGravity: 70.0,
      magnetStyle: MagnetStyle.arcs,
      magnetColors: [Color(0xFFCC1100)],
      ambientStyle: AmbientStyle.embers,
      ambientColors: [Color(0xFF8B0000), Color(0xFFCC1100)],
      ambientCount: 20,
      wallStyle: WallStyle.clean,
      wallAccentColor: Color(0xFF8B0000),
      wallGlowIntensity: 0.2,
    ),

    // 3. Forest Spirit
    VisualTheme(
      id: 't1_forest_spirit',
      displayName: 'Forest Spirit',
      tier: 1,
      variation: 2,
      ballShape: BallShape.leaf,
      ballColors: [Color(0xFF00C853), Color(0xFF1B5E20)],
      ballGlowRadius: 9.0,
      ballGlowIntensity: 0.28,
      ballEffect: BallEffect.breathe,
      ballEffectSpeed: 0.7,
      trailStyle: TrailStyle.sparkles,
      trailColors: [Color(0xFF69F0AE), Color(0xFF00C853)],
      trailWidth: 1.0,
      trailLife: 1.3,
      trailDensity: 2,
      obstacleStyle: ObstacleStyle.frost,
      obstacleColors: [Color(0xFF2E7D32), Color(0xFF1B5E20)],
      obstacleGlowIntensity: 0.25,
      explosionPattern: ExplosionPattern.bloom,
      explosionColors: [Color(0xFF69F0AE), Color(0xFF00C853), Color(0xFFA5D6A7)],
      explosionParticleCount: 90,
      explosionLife: 1.5,
      explosionGravity: 40.0,
      magnetStyle: MagnetStyle.tendrils,
      magnetColors: [Color(0xFF00C853)],
      ambientStyle: AmbientStyle.leaves,
      ambientColors: [Color(0xFF69F0AE), Color(0xFF00C853)],
      ambientCount: 25,
      wallStyle: WallStyle.clean,
      wallAccentColor: Color(0xFF2E7D32),
      wallGlowIntensity: 0.2,
    ),

    // 4. Ocean Deep
    VisualTheme(
      id: 't1_ocean_deep',
      displayName: 'Ocean Deep',
      tier: 1,
      variation: 3,
      ballShape: BallShape.circle,
      ballColors: [Color(0xFF003366), Color(0xFF00897B)],
      ballGlowRadius: 12.0,
      ballGlowIntensity: 0.32,
      ballEffect: BallEffect.breathe,
      ballEffectSpeed: 0.6,
      trailStyle: TrailStyle.bubbles,
      trailColors: [Color(0xFF00897B), Color(0xFF4DD0E1)],
      trailWidth: 1.0,
      trailLife: 1.4,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.pulse,
      obstacleColors: [Color(0xFF003366), Color(0xFF006064)],
      obstacleGlowIntensity: 0.30,
      explosionPattern: ExplosionPattern.cascade,
      explosionColors: [Color(0xFF4DD0E1), Color(0xFF00897B), Color(0xFF003366)],
      explosionParticleCount: 110,
      explosionLife: 1.4,
      explosionGravity: 30.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFF00897B)],
      ambientStyle: AmbientStyle.bubbles,
      ambientColors: [Color(0xFF4DD0E1), Color(0xFF80DEEA)],
      ambientCount: 35,
      wallStyle: WallStyle.pulse,
      wallAccentColor: Color(0xFF006064),
      wallGlowIntensity: 0.25,
    ),

    // 5. Sunset Blaze
    VisualTheme(
      id: 't1_sunset_blaze',
      displayName: 'Sunset Blaze',
      tier: 1,
      variation: 4,
      ballShape: BallShape.star5,
      ballColors: [Color(0xFFFF6D00), Color(0xFFFFAB00)],
      ballGlowRadius: 11.0,
      ballGlowIntensity: 0.38,
      ballEffect: BallEffect.pulse,
      ballEffectSpeed: 1.0,
      trailStyle: TrailStyle.embers,
      trailColors: [Color(0xFFFF6D00), Color(0xFFFF8F00), Color(0xFFFFCC02)],
      trailWidth: 1.3,
      trailLife: 0.9,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.solid,
      obstacleColors: [Color(0xFFBF360C), Color(0xFFE65100)],
      obstacleGlowIntensity: 0.30,
      explosionPattern: ExplosionPattern.fountain,
      explosionColors: [Color(0xFFFFAB00), Color(0xFFFF6D00), Color(0xFFDD2C00)],
      explosionParticleCount: 130,
      explosionLife: 1.2,
      explosionGravity: 80.0,
      magnetStyle: MagnetStyle.particles,
      magnetColors: [Color(0xFFFF6D00)],
      ambientStyle: AmbientStyle.embers,
      ambientColors: [Color(0xFFFF6D00), Color(0xFFFFAB00)],
      ambientCount: 22,
      wallStyle: WallStyle.flame,
      wallAccentColor: Color(0xFFFF6D00),
      wallGlowIntensity: 0.35,
    ),

    // 6. Violet Storm
    VisualTheme(
      id: 't1_violet_storm',
      displayName: 'Violet Storm',
      tier: 1,
      variation: 5,
      ballShape: BallShape.pentagon,
      ballColors: [Color(0xFF7B1FA2), Color(0xFFAB47BC)],
      ballGlowRadius: 9.0,
      ballGlowIntensity: 0.33,
      ballEffect: BallEffect.flicker,
      ballEffectSpeed: 1.5,
      trailStyle: TrailStyle.lightning,
      trailColors: [Color(0xFFAB47BC), Color(0xFFCE93D8)],
      trailWidth: 1.1,
      trailLife: 0.8,
      trailDensity: 2,
      obstacleStyle: ObstacleStyle.electric,
      obstacleColors: [Color(0xFF6A1B9A), Color(0xFF4A148C)],
      obstacleGlowIntensity: 0.40,
      explosionPattern: ExplosionPattern.lightning,
      explosionColors: [Color(0xFFCE93D8), Color(0xFFAB47BC), Color(0xFFFFFFFF)],
      explosionParticleCount: 100,
      explosionLife: 1.0,
      explosionGravity: 50.0,
      magnetStyle: MagnetStyle.electric,
      magnetColors: [Color(0xFFAB47BC)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFFCE93D8)],
      ambientCount: 18,
      wallStyle: WallStyle.clean,
      wallAccentColor: Color(0xFF7B1FA2),
      wallGlowIntensity: 0.25,
    ),

    // 7. Golden Hour
    VisualTheme(
      id: 't1_golden_hour',
      displayName: 'Golden Hour',
      tier: 1,
      variation: 6,
      ballShape: BallShape.crown,
      ballColors: [Color(0xFFFFD700), Color(0xFFFFC107)],
      ballGlowRadius: 10.0,
      ballGlowIntensity: 0.40,
      ballEffect: BallEffect.breathe,
      ballEffectSpeed: 0.8,
      trailStyle: TrailStyle.dots,
      trailColors: [Color(0xFFFFD700), Color(0xFFFFA000)],
      trailWidth: 1.0,
      trailLife: 1.2,
      trailDensity: 2,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFFB8860B), Color(0xFF8D6E04)],
      obstacleGlowIntensity: 0.35,
      explosionPattern: ExplosionPattern.spiral,
      explosionColors: [Color(0xFFFFD700), Color(0xFFFFC107), Color(0xFFFFF176)],
      explosionParticleCount: 95,
      explosionLife: 1.3,
      explosionGravity: 55.0,
      magnetStyle: MagnetStyle.lines,
      magnetColors: [Color(0xFFFFD700)],
      ambientStyle: AmbientStyle.dust,
      ambientColors: [Color(0xFFFFD700), Color(0xFFFFC107)],
      ambientCount: 20,
      wallStyle: WallStyle.clean,
      wallAccentColor: Color(0xFFB8860B),
      wallGlowIntensity: 0.25,
    ),

    // 8. Arctic Frost
    VisualTheme(
      id: 't1_arctic_frost',
      displayName: 'Arctic Frost',
      tier: 1,
      variation: 7,
      ballShape: BallShape.snowflake,
      ballColors: [Color(0xFFB3E5FC), Color(0xFF81D4FA)],
      ballGlowRadius: 11.0,
      ballGlowIntensity: 0.30,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 0.5,
      trailStyle: TrailStyle.crystals,
      trailColors: [Color(0xFF81D4FA), Color(0xFF4FC3F7), Color(0xFFE1F5FE)],
      trailWidth: 1.0,
      trailLife: 1.5,
      trailDensity: 2,
      obstacleStyle: ObstacleStyle.frost,
      obstacleColors: [Color(0xFF0288D1), Color(0xFF01579B)],
      obstacleGlowIntensity: 0.30,
      explosionPattern: ExplosionPattern.shatter,
      explosionColors: [Color(0xFFE1F5FE), Color(0xFF81D4FA), Color(0xFFB3E5FC)],
      explosionParticleCount: 140,
      explosionLife: 1.6,
      explosionGravity: 35.0,
      magnetStyle: MagnetStyle.pulses,
      magnetColors: [Color(0xFF81D4FA)],
      ambientStyle: AmbientStyle.snow,
      ambientColors: [Color(0xFFE1F5FE), Color(0xFFB3E5FC)],
      ambientCount: 40,
      wallStyle: WallStyle.frost,
      wallAccentColor: Color(0xFF4FC3F7),
      wallGlowIntensity: 0.28,
    ),

    // 9. Copper Forge
    VisualTheme(
      id: 't1_copper_forge',
      displayName: 'Copper Forge',
      tier: 1,
      variation: 8,
      ballShape: BallShape.gear,
      ballColors: [Color(0xFFB87333), Color(0xFFCD7F32)],
      ballGlowRadius: 7.0,
      ballGlowIntensity: 0.25,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 1.0,
      trailStyle: TrailStyle.embers,
      trailColors: [Color(0xFFCD7F32), Color(0xFF8B4513)],
      trailWidth: 1.5,
      trailLife: 0.8,
      trailDensity: 2,
      obstacleStyle: ObstacleStyle.cracked,
      obstacleColors: [Color(0xFF6D3A1A), Color(0xFF4E2A0C)],
      obstacleGlowIntensity: 0.20,
      explosionPattern: ExplosionPattern.burst,
      explosionColors: [Color(0xFFCD7F32), Color(0xFFFF8C00), Color(0xFF8B4513)],
      explosionParticleCount: 85,
      explosionLife: 1.0,
      explosionGravity: 90.0,
      magnetStyle: MagnetStyle.chains,
      magnetColors: [Color(0xFFB87333)],
      ambientStyle: AmbientStyle.ash,
      ambientColors: [Color(0xFF8B4513), Color(0xFFCD7F32)],
      ambientCount: 15,
      wallStyle: WallStyle.clean,
      wallAccentColor: Color(0xFF6D3A1A),
      wallGlowIntensity: 0.18,
    ),

    // 10. Rose Quartz
    VisualTheme(
      id: 't1_rose_quartz',
      displayName: 'Rose Quartz',
      tier: 1,
      variation: 9,
      ballShape: BallShape.diamond,
      ballColors: [Color(0xFFF48FB1), Color(0xFFF06292)],
      ballGlowRadius: 10.0,
      ballGlowIntensity: 0.32,
      ballEffect: BallEffect.pulse,
      ballEffectSpeed: 0.8,
      trailStyle: TrailStyle.sparkles,
      trailColors: [Color(0xFFF48FB1), Color(0xFFEC407A), Color(0xFFFCE4EC)],
      trailWidth: 1.0,
      trailLife: 1.3,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFFAD1457), Color(0xFF880E4F)],
      obstacleGlowIntensity: 0.30,
      explosionPattern: ExplosionPattern.bloom,
      explosionColors: [Color(0xFFF48FB1), Color(0xFFFCE4EC), Color(0xFFEC407A)],
      explosionParticleCount: 100,
      explosionLife: 1.4,
      explosionGravity: 35.0,
      magnetStyle: MagnetStyle.particles,
      magnetColors: [Color(0xFFF48FB1)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFFF48FB1), Color(0xFFFCE4EC)],
      ambientCount: 28,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFFF06292),
      wallGlowIntensity: 0.30,
    ),
  ];

  // ---------------------------------------------------------------------------
  // Tier 2 — "Ascension" (Score 200)
  // ---------------------------------------------------------------------------
  static const _tier2 = <VisualTheme>[
    // 11. Plasma Core
    VisualTheme(
      id: 't2_plasma_core',
      displayName: 'Plasma Core',
      tier: 2,
      variation: 0,
      ballShape: BallShape.circle,
      ballColors: [Color(0xFFFF1493), Color(0xFF00BFFF)],
      ballGlowRadius: 14.0,
      ballGlowIntensity: 0.45,
      ballEffect: BallEffect.orbit,
      ballEffectSpeed: 1.4,
      trailStyle: TrailStyle.streaks,
      trailColors: [Color(0xFFFF1493), Color(0xFF00BFFF), Color(0xFFFF69B4)],
      trailWidth: 1.5,
      trailLife: 1.0,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.pulse,
      obstacleColors: [Color(0xFFB2005E), Color(0xFF006994)],
      obstacleGlowIntensity: 0.45,
      explosionPattern: ExplosionPattern.nova,
      explosionColors: [Color(0xFFFF1493), Color(0xFF00BFFF), Color(0xFFFFFFFF)],
      explosionParticleCount: 160,
      explosionLife: 1.5,
      explosionGravity: 45.0,
      magnetStyle: MagnetStyle.electric,
      magnetColors: [Color(0xFFFF1493), Color(0xFF00BFFF)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFFFF69B4), Color(0xFF87CEFA)],
      ambientCount: 35,
      wallStyle: WallStyle.pulse,
      wallAccentColor: Color(0xFFFF1493),
      wallGlowIntensity: 0.35,
    ),

    // 12. Void Walker
    VisualTheme(
      id: 't2_void_walker',
      displayName: 'Void Walker',
      tier: 2,
      variation: 1,
      ballShape: BallShape.eye,
      ballColors: [Color(0xFF2D0054), Color(0xFF4A0080)],
      ballGlowRadius: 13.0,
      ballGlowIntensity: 0.38,
      ballEffect: BallEffect.breathe,
      ballEffectSpeed: 0.6,
      trailStyle: TrailStyle.shadows,
      trailColors: [Color(0xFF2D0054), Color(0xFF1A0033), Color(0xFF6A0DAD)],
      trailWidth: 1.8,
      trailLife: 1.5,
      trailDensity: 2,
      obstacleStyle: ObstacleStyle.shadow,
      obstacleColors: [Color(0xFF1A0033), Color(0xFF0D001A)],
      obstacleGlowIntensity: 0.25,
      explosionPattern: ExplosionPattern.vortex,
      explosionColors: [Color(0xFF6A0DAD), Color(0xFF2D0054), Color(0xFF000000)],
      explosionParticleCount: 120,
      explosionLife: 1.8,
      explosionGravity: 20.0,
      magnetStyle: MagnetStyle.tendrils,
      magnetColors: [Color(0xFF4A0080)],
      ambientStyle: AmbientStyle.dust,
      ambientColors: [Color(0xFF2D0054), Color(0xFF6A0DAD)],
      ambientCount: 20,
      wallStyle: WallStyle.drip,
      wallAccentColor: Color(0xFF4A0080),
      wallGlowIntensity: 0.20,
    ),

    // 13. Solar Flare
    VisualTheme(
      id: 't2_solar_flare',
      displayName: 'Solar Flare',
      tier: 2,
      variation: 2,
      ballShape: BallShape.circle,
      ballColors: [Color(0xFFFFF9C4), Color(0xFFFFEE58)],
      ballGlowRadius: 16.0,
      ballGlowIntensity: 0.50,
      ballEffect: BallEffect.corona,
      ballEffectSpeed: 1.0,
      trailStyle: TrailStyle.flames,
      trailColors: [Color(0xFFFFEE58), Color(0xFFFF8F00), Color(0xFFFF6D00)],
      trailWidth: 1.6,
      trailLife: 0.9,
      trailDensity: 4,
      obstacleStyle: ObstacleStyle.flame,
      obstacleColors: [Color(0xFFE65100), Color(0xFFBF360C)],
      obstacleGlowIntensity: 0.50,
      explosionPattern: ExplosionPattern.burst,
      explosionColors: [Color(0xFFFFF9C4), Color(0xFFFFEE58), Color(0xFFFF6D00)],
      explosionParticleCount: 180,
      explosionLife: 1.2,
      explosionGravity: 65.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFFFFEE58), Color(0xFFFF8F00)],
      ambientStyle: AmbientStyle.embers,
      ambientColors: [Color(0xFFFF8F00), Color(0xFFFFCC02)],
      ambientCount: 30,
      wallStyle: WallStyle.flame,
      wallAccentColor: Color(0xFFFF8F00),
      wallGlowIntensity: 0.40,
      invertedBallColors: [Color(0xFF5D4037), Color(0xFF4E342E)],
      invertedTrailColors: [Color(0xFF4E342E), Color(0xFFBF360C), Color(0xFFE65100)],
      invertedObstacleColors: [Color(0xFFBF360C), Color(0xFF8D3A00)],
    ),

    // 14. Toxic Spill
    VisualTheme(
      id: 't2_toxic_spill',
      displayName: 'Toxic Spill',
      tier: 2,
      variation: 3,
      ballShape: BallShape.hexagon,
      ballColors: [Color(0xFF39FF14), Color(0xFF76FF03)],
      ballGlowRadius: 12.0,
      ballGlowIntensity: 0.42,
      ballEffect: BallEffect.pulse,
      ballEffectSpeed: 1.3,
      trailStyle: TrailStyle.droplets,
      trailColors: [Color(0xFF76FF03), Color(0xFF39FF14), Color(0xFF00E676)],
      trailWidth: 1.2,
      trailLife: 1.2,
      trailDensity: 4,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFF1B5E20), Color(0xFF33691E)],
      obstacleGlowIntensity: 0.40,
      explosionPattern: ExplosionPattern.cascade,
      explosionColors: [Color(0xFF76FF03), Color(0xFF39FF14), Color(0xFFB2FF59)],
      explosionParticleCount: 130,
      explosionLife: 1.3,
      explosionGravity: 50.0,
      magnetStyle: MagnetStyle.particles,
      magnetColors: [Color(0xFF39FF14)],
      ambientStyle: AmbientStyle.bubbles,
      ambientColors: [Color(0xFF76FF03), Color(0xFF39FF14)],
      ambientCount: 25,
      wallStyle: WallStyle.drip,
      wallAccentColor: Color(0xFF39FF14),
      wallGlowIntensity: 0.35,
    ),

    // 15. Chrome Machine
    VisualTheme(
      id: 't2_chrome_machine',
      displayName: 'Chrome Machine',
      tier: 2,
      variation: 4,
      ballShape: BallShape.cube,
      ballColors: [Color(0xFFC0C0C0), Color(0xFF808080)],
      ballGlowRadius: 8.0,
      ballGlowIntensity: 0.28,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 1.2,
      trailStyle: TrailStyle.streaks,
      trailColors: [Color(0xFFC0C0C0), Color(0xFF9E9E9E)],
      trailWidth: 1.4,
      trailLife: 0.7,
      trailDensity: 2,
      obstacleStyle: ObstacleStyle.stripe,
      obstacleColors: [Color(0xFF616161), Color(0xFF424242)],
      obstacleGlowIntensity: 0.22,
      explosionPattern: ExplosionPattern.shatter,
      explosionColors: [Color(0xFFC0C0C0), Color(0xFFE0E0E0), Color(0xFF757575)],
      explosionParticleCount: 150,
      explosionLife: 1.0,
      explosionGravity: 100.0,
      magnetStyle: MagnetStyle.lines,
      magnetColors: [Color(0xFFC0C0C0)],
      ambientStyle: AmbientStyle.dust,
      ambientColors: [Color(0xFF9E9E9E)],
      ambientCount: 12,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFF9E9E9E),
      wallGlowIntensity: 0.22,
    ),

    // 16. Blood Moon
    VisualTheme(
      id: 't2_blood_moon',
      displayName: 'Blood Moon',
      tier: 2,
      variation: 5,
      ballShape: BallShape.crescent,
      ballColors: [Color(0xFFB71C1C), Color(0xFF880E0E)],
      ballGlowRadius: 12.0,
      ballGlowIntensity: 0.40,
      ballEffect: BallEffect.breathe,
      ballEffectSpeed: 0.5,
      trailStyle: TrailStyle.shadows,
      trailColors: [Color(0xFF880E0E), Color(0xFF4A0000), Color(0xFF210000)],
      trailWidth: 1.6,
      trailLife: 1.4,
      trailDensity: 2,
      obstacleStyle: ObstacleStyle.shadow,
      obstacleColors: [Color(0xFF4A0000), Color(0xFF210000)],
      obstacleGlowIntensity: 0.30,
      explosionPattern: ExplosionPattern.ring,
      explosionColors: [Color(0xFFB71C1C), Color(0xFF880E0E), Color(0xFFFF1744)],
      explosionParticleCount: 110,
      explosionLife: 1.5,
      explosionGravity: 40.0,
      magnetStyle: MagnetStyle.arcs,
      magnetColors: [Color(0xFFB71C1C)],
      ambientStyle: AmbientStyle.ash,
      ambientColors: [Color(0xFF4A0000), Color(0xFF880E0E)],
      ambientCount: 18,
      wallStyle: WallStyle.pulse,
      wallAccentColor: Color(0xFFB71C1C),
      wallGlowIntensity: 0.30,
    ),

    // 17. Digital Rain
    VisualTheme(
      id: 't2_digital_rain',
      displayName: 'Digital Rain',
      tier: 2,
      variation: 6,
      ballShape: BallShape.cross,
      ballColors: [Color(0xFF00FF41), Color(0xFF00CC33)],
      ballGlowRadius: 10.0,
      ballGlowIntensity: 0.35,
      ballEffect: BallEffect.flicker,
      ballEffectSpeed: 2.0,
      trailStyle: TrailStyle.code,
      trailColors: [Color(0xFF00FF41), Color(0xFF00CC33), Color(0xFF008F11)],
      trailWidth: 1.0,
      trailLife: 1.6,
      trailDensity: 5,
      obstacleStyle: ObstacleStyle.stripe,
      obstacleColors: [Color(0xFF003B00), Color(0xFF001A00)],
      obstacleGlowIntensity: 0.30,
      explosionPattern: ExplosionPattern.fractal,
      explosionColors: [Color(0xFF00FF41), Color(0xFF00CC33), Color(0xFF66FF66)],
      explosionParticleCount: 140,
      explosionLife: 1.3,
      explosionGravity: 25.0,
      magnetStyle: MagnetStyle.pulses,
      magnetColors: [Color(0xFF00FF41)],
      ambientStyle: AmbientStyle.rain,
      ambientColors: [Color(0xFF00FF41), Color(0xFF00CC33)],
      ambientCount: 45,
      wallStyle: WallStyle.electric,
      wallAccentColor: Color(0xFF00FF41),
      wallGlowIntensity: 0.30,
    ),

    // 18. Sapphire Crown
    VisualTheme(
      id: 't2_sapphire_crown',
      displayName: 'Sapphire Crown',
      tier: 2,
      variation: 7,
      ballShape: BallShape.crown,
      ballColors: [Color(0xFF1565C0), Color(0xFFFFD700)],
      ballGlowRadius: 12.0,
      ballGlowIntensity: 0.40,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 0.8,
      trailStyle: TrailStyle.sparkles,
      trailColors: [Color(0xFF1976D2), Color(0xFFFFD700), Color(0xFF64B5F6)],
      trailWidth: 1.2,
      trailLife: 1.3,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFF0D47A1), Color(0xFF0A3880)],
      obstacleGlowIntensity: 0.38,
      explosionPattern: ExplosionPattern.spiral,
      explosionColors: [Color(0xFF1565C0), Color(0xFFFFD700), Color(0xFF90CAF9)],
      explosionParticleCount: 120,
      explosionLife: 1.4,
      explosionGravity: 50.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFF1565C0), Color(0xFFFFD700)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFF64B5F6), Color(0xFFFFD700)],
      ambientCount: 30,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFF1565C0),
      wallGlowIntensity: 0.35,
    ),

    // 19. Phantom Flame
    VisualTheme(
      id: 't2_phantom_flame',
      displayName: 'Phantom Flame',
      tier: 2,
      variation: 8,
      ballShape: BallShape.circle,
      ballColors: [Color(0xFFECEFF1), Color(0xFFB0BEC5)],
      ballGlowRadius: 14.0,
      ballGlowIntensity: 0.42,
      ballEffect: BallEffect.breathe,
      ballEffectSpeed: 0.7,
      trailStyle: TrailStyle.flames,
      trailColors: [Color(0xFFB0BEC5), Color(0xFF78909C), Color(0xFFCFD8DC)],
      trailWidth: 1.4,
      trailLife: 1.1,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.frost,
      obstacleColors: [Color(0xFF546E7A), Color(0xFF37474F)],
      obstacleGlowIntensity: 0.30,
      explosionPattern: ExplosionPattern.implosion,
      explosionColors: [Color(0xFFECEFF1), Color(0xFFB0BEC5), Color(0xFFFFFFFF)],
      explosionParticleCount: 100,
      explosionLife: 1.6,
      explosionGravity: 15.0,
      magnetStyle: MagnetStyle.tendrils,
      magnetColors: [Color(0xFFB0BEC5)],
      ambientStyle: AmbientStyle.dust,
      ambientColors: [Color(0xFFCFD8DC), Color(0xFFB0BEC5)],
      ambientCount: 22,
      wallStyle: WallStyle.clean,
      wallAccentColor: Color(0xFF78909C),
      wallGlowIntensity: 0.25,
      invertedBallColors: [Color(0xFF37474F), Color(0xFF455A64)],
      invertedTrailColors: [Color(0xFF455A64), Color(0xFF546E7A), Color(0xFF37474F)],
      invertedObstacleColors: [Color(0xFF546E7A), Color(0xFF37474F)],
    ),

    // 20. Thunder God
    VisualTheme(
      id: 't2_thunder_god',
      displayName: 'Thunder God',
      tier: 2,
      variation: 9,
      ballShape: BallShape.bolt,
      ballColors: [Color(0xFFFFEB3B), Color(0xFFFDD835)],
      ballGlowRadius: 15.0,
      ballGlowIntensity: 0.48,
      ballEffect: BallEffect.flicker,
      ballEffectSpeed: 2.5,
      trailStyle: TrailStyle.lightning,
      trailColors: [Color(0xFFFFEB3B), Color(0xFFFFFFFF), Color(0xFFFBC02D)],
      trailWidth: 1.3,
      trailLife: 0.6,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.electric,
      obstacleColors: [Color(0xFFF57F17), Color(0xFFE65100)],
      obstacleGlowIntensity: 0.50,
      explosionPattern: ExplosionPattern.lightning,
      explosionColors: [Color(0xFFFFEB3B), Color(0xFFFFFFFF), Color(0xFFFBC02D)],
      explosionParticleCount: 170,
      explosionLife: 0.9,
      explosionGravity: 30.0,
      magnetStyle: MagnetStyle.electric,
      magnetColors: [Color(0xFFFFEB3B), Color(0xFFFFFFFF)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFFFFEB3B), Color(0xFFFFF176)],
      ambientCount: 25,
      wallStyle: WallStyle.electric,
      wallAccentColor: Color(0xFFFFEB3B),
      wallGlowIntensity: 0.45,
      invertedBallColors: [Color(0xFF5D4037), Color(0xFF3E2723)],
      invertedTrailColors: [Color(0xFF5D4037), Color(0xFF3E2723), Color(0xFF4E342E)],
      invertedObstacleColors: [Color(0xFFE65100), Color(0xFFBF360C)],
    ),
  ];

  // ---------------------------------------------------------------------------
  // Tier 3 — "Mastery" (Score 300)
  // ---------------------------------------------------------------------------
  static const _tier3 = <VisualTheme>[
    // 21. Nebula Drift
    VisualTheme(
      id: 't3_nebula_drift',
      displayName: 'Nebula Drift',
      tier: 3,
      variation: 0,
      ballShape: BallShape.spiral,
      ballColors: [Color(0xFFF8BBD0), Color(0xFFCE93D8)],
      ballGlowRadius: 15.0,
      ballGlowIntensity: 0.42,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 0.6,
      trailStyle: TrailStyle.sparkles,
      trailColors: [Color(0xFFF8BBD0), Color(0xFFCE93D8), Color(0xFFB39DDB)],
      trailWidth: 1.2,
      trailLife: 1.6,
      trailDensity: 4,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFF7B1FA2), Color(0xFF4A148C)],
      obstacleGlowIntensity: 0.38,
      explosionPattern: ExplosionPattern.bloom,
      explosionColors: [Color(0xFFF8BBD0), Color(0xFFCE93D8), Color(0xFFB39DDB), Color(0xFFE1BEE7)],
      explosionParticleCount: 160,
      explosionLife: 1.8,
      explosionGravity: 20.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFFCE93D8), Color(0xFFB39DDB)],
      ambientStyle: AmbientStyle.stars,
      ambientColors: [Color(0xFFF8BBD0), Color(0xFFCE93D8), Color(0xFFB39DDB)],
      ambientCount: 50,
      wallStyle: WallStyle.pulse,
      wallAccentColor: Color(0xFFCE93D8),
      wallGlowIntensity: 0.30,
    ),

    // 22. Lava King
    VisualTheme(
      id: 't3_lava_king',
      displayName: 'Lava King',
      tier: 3,
      variation: 1,
      ballShape: BallShape.circle,
      ballColors: [Color(0xFFFF5722), Color(0xFF1A1A1A)],
      ballGlowRadius: 14.0,
      ballGlowIntensity: 0.50,
      ballEffect: BallEffect.morph,
      ballEffectSpeed: 0.8,
      trailStyle: TrailStyle.embers,
      trailColors: [Color(0xFFFF5722), Color(0xFFFF9800), Color(0xFFDD2C00)],
      trailWidth: 2.0,
      trailLife: 1.0,
      trailDensity: 5,
      obstacleStyle: ObstacleStyle.flame,
      obstacleColors: [Color(0xFFBF360C), Color(0xFF3E2723)],
      obstacleGlowIntensity: 0.50,
      explosionPattern: ExplosionPattern.fountain,
      explosionColors: [Color(0xFFFF5722), Color(0xFFFF9800), Color(0xFFFFEB3B), Color(0xFF1A1A1A)],
      explosionParticleCount: 200,
      explosionLife: 1.4,
      explosionGravity: 100.0,
      magnetStyle: MagnetStyle.arcs,
      magnetColors: [Color(0xFFFF5722), Color(0xFFFF9800)],
      ambientStyle: AmbientStyle.embers,
      ambientColors: [Color(0xFFFF5722), Color(0xFFFF9800)],
      ambientCount: 40,
      wallStyle: WallStyle.flame,
      wallAccentColor: Color(0xFFFF5722),
      wallGlowIntensity: 0.45,
    ),

    // 23. Ice Monarch
    VisualTheme(
      id: 't3_ice_monarch',
      displayName: 'Ice Monarch',
      tier: 3,
      variation: 2,
      ballShape: BallShape.snowflake,
      ballColors: [Color(0xFF80D8FF), Color(0xFFE0F7FA)],
      ballGlowRadius: 14.0,
      ballGlowIntensity: 0.40,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 0.4,
      trailStyle: TrailStyle.crystals,
      trailColors: [Color(0xFF80D8FF), Color(0xFFB2EBF2), Color(0xFFE0F7FA)],
      trailWidth: 1.3,
      trailLife: 1.8,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.frost,
      obstacleColors: [Color(0xFF0097A7), Color(0xFF006064)],
      obstacleGlowIntensity: 0.38,
      explosionPattern: ExplosionPattern.shatter,
      explosionColors: [Color(0xFFE0F7FA), Color(0xFF80D8FF), Color(0xFFB2EBF2), Color(0xFFFFFFFF)],
      explosionParticleCount: 180,
      explosionLife: 1.7,
      explosionGravity: 25.0,
      magnetStyle: MagnetStyle.pulses,
      magnetColors: [Color(0xFF80D8FF), Color(0xFFB2EBF2)],
      ambientStyle: AmbientStyle.snow,
      ambientColors: [Color(0xFFE0F7FA), Color(0xFFFFFFFF)],
      ambientCount: 55,
      wallStyle: WallStyle.frost,
      wallAccentColor: Color(0xFF80D8FF),
      wallGlowIntensity: 0.35,
      invertedBallColors: [Color(0xFF006064), Color(0xFF004D40)],
      invertedTrailColors: [Color(0xFF006064), Color(0xFF00838F), Color(0xFF004D40)],
      invertedObstacleColors: [Color(0xFF00838F), Color(0xFF005662)],
    ),

    // 24. Shadow Blade
    VisualTheme(
      id: 't3_shadow_blade',
      displayName: 'Shadow Blade',
      tier: 3,
      variation: 3,
      ballShape: BallShape.cross,
      ballColors: [Color(0xFF0A0A0A), Color(0xFFD50000)],
      ballGlowRadius: 10.0,
      ballGlowIntensity: 0.35,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 1.8,
      trailStyle: TrailStyle.streaks,
      trailColors: [Color(0xFFD50000), Color(0xFF0A0A0A), Color(0xFF8B0000)],
      trailWidth: 1.6,
      trailLife: 0.7,
      trailDensity: 2,
      obstacleStyle: ObstacleStyle.shadow,
      obstacleColors: [Color(0xFF1A1A1A), Color(0xFF0A0A0A)],
      obstacleGlowIntensity: 0.20,
      explosionPattern: ExplosionPattern.burst,
      explosionColors: [Color(0xFFD50000), Color(0xFF0A0A0A), Color(0xFFFF1744)],
      explosionParticleCount: 130,
      explosionLife: 0.8,
      explosionGravity: 120.0,
      magnetStyle: MagnetStyle.chains,
      magnetColors: [Color(0xFFD50000)],
      ambientStyle: AmbientStyle.ash,
      ambientColors: [Color(0xFF1A1A1A), Color(0xFF0A0A0A)],
      ambientCount: 15,
      wallStyle: WallStyle.crack,
      wallAccentColor: Color(0xFFD50000),
      wallGlowIntensity: 0.25,
    ),

    // 25. Aurora Borealis
    VisualTheme(
      id: 't3_aurora_borealis',
      displayName: 'Aurora Borealis',
      tier: 3,
      variation: 4,
      ballShape: BallShape.ring,
      ballColors: [Color(0xFF00E676), Color(0xFF2979FF), Color(0xFFAA00FF)],
      ballGlowRadius: 16.0,
      ballGlowIntensity: 0.45,
      ballEffect: BallEffect.prismatic,
      ballEffectSpeed: 0.8,
      trailStyle: TrailStyle.ribbons,
      trailColors: [Color(0xFF00E676), Color(0xFF2979FF), Color(0xFFAA00FF), Color(0xFF00BFA5)],
      trailWidth: 1.5,
      trailLife: 1.6,
      trailDensity: 4,
      obstacleStyle: ObstacleStyle.pulse,
      obstacleColors: [Color(0xFF00695C), Color(0xFF1A237E)],
      obstacleGlowIntensity: 0.40,
      explosionPattern: ExplosionPattern.bloom,
      explosionColors: [Color(0xFF00E676), Color(0xFF2979FF), Color(0xFFAA00FF), Color(0xFF00BFA5)],
      explosionParticleCount: 170,
      explosionLife: 1.8,
      explosionGravity: 15.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFF00E676), Color(0xFF2979FF)],
      ambientStyle: AmbientStyle.fireflies,
      ambientColors: [Color(0xFF00E676), Color(0xFF2979FF), Color(0xFFAA00FF)],
      ambientCount: 45,
      wallStyle: WallStyle.pulse,
      wallAccentColor: Color(0xFF00E676),
      wallGlowIntensity: 0.35,
    ),

    // 26. Obsidian Mirror
    VisualTheme(
      id: 't3_obsidian_mirror',
      displayName: 'Obsidian Mirror',
      tier: 3,
      variation: 5,
      ballShape: BallShape.diamond,
      ballColors: [Color(0xFF0D0D0D), Color(0xFF6200EA)],
      ballGlowRadius: 12.0,
      ballGlowIntensity: 0.38,
      ballEffect: BallEffect.prismatic,
      ballEffectSpeed: 0.6,
      trailStyle: TrailStyle.sparkles,
      trailColors: [Color(0xFF6200EA), Color(0xFF304FFE), Color(0xFFFF4081)],
      trailWidth: 1.0,
      trailLife: 1.4,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.shadow,
      obstacleColors: [Color(0xFF0D0D0D), Color(0xFF1A1A2E)],
      obstacleGlowIntensity: 0.28,
      explosionPattern: ExplosionPattern.ring,
      explosionColors: [Color(0xFF6200EA), Color(0xFF304FFE), Color(0xFFFF4081), Color(0xFF00BCD4)],
      explosionParticleCount: 140,
      explosionLife: 1.5,
      explosionGravity: 35.0,
      magnetStyle: MagnetStyle.tendrils,
      magnetColors: [Color(0xFF6200EA)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFF6200EA), Color(0xFF304FFE)],
      ambientCount: 25,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFF6200EA),
      wallGlowIntensity: 0.30,
    ),

    // 27. Storm Eye
    VisualTheme(
      id: 't3_storm_eye',
      displayName: 'Storm Eye',
      tier: 3,
      variation: 6,
      ballShape: BallShape.spiral,
      ballColors: [Color(0xFF9E9E9E), Color(0xFFE0E0E0)],
      ballGlowRadius: 13.0,
      ballGlowIntensity: 0.35,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 1.5,
      trailStyle: TrailStyle.waves,
      trailColors: [Color(0xFF9E9E9E), Color(0xFFBDBDBD), Color(0xFF616161)],
      trailWidth: 1.8,
      trailLife: 1.2,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.pulse,
      obstacleColors: [Color(0xFF424242), Color(0xFF212121)],
      obstacleGlowIntensity: 0.32,
      explosionPattern: ExplosionPattern.vortex,
      explosionColors: [Color(0xFFE0E0E0), Color(0xFF9E9E9E), Color(0xFFFFFFFF)],
      explosionParticleCount: 150,
      explosionLife: 1.6,
      explosionGravity: 30.0,
      magnetStyle: MagnetStyle.electric,
      magnetColors: [Color(0xFF9E9E9E), Color(0xFFBDBDBD)],
      ambientStyle: AmbientStyle.rain,
      ambientColors: [Color(0xFF9E9E9E), Color(0xFFBDBDBD)],
      ambientCount: 50,
      wallStyle: WallStyle.electric,
      wallAccentColor: Color(0xFF9E9E9E),
      wallGlowIntensity: 0.30,
      invertedBallColors: [Color(0xFF424242), Color(0xFF303030)],
      invertedTrailColors: [Color(0xFF424242), Color(0xFF37474F), Color(0xFF212121)],
      invertedObstacleColors: [Color(0xFF424242), Color(0xFF212121)],
    ),

    // 28. Jade Emperor
    VisualTheme(
      id: 't3_jade_emperor',
      displayName: 'Jade Emperor',
      tier: 3,
      variation: 7,
      ballShape: BallShape.hexagon,
      ballColors: [Color(0xFF00A86B), Color(0xFFFFD700)],
      ballGlowRadius: 12.0,
      ballGlowIntensity: 0.40,
      ballEffect: BallEffect.breathe,
      ballEffectSpeed: 0.7,
      trailStyle: TrailStyle.sparkles,
      trailColors: [Color(0xFF00A86B), Color(0xFFFFD700), Color(0xFF50C878)],
      trailWidth: 1.2,
      trailLife: 1.4,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFF006B3C), Color(0xFF004D28)],
      obstacleGlowIntensity: 0.38,
      explosionPattern: ExplosionPattern.spiral,
      explosionColors: [Color(0xFF00A86B), Color(0xFFFFD700), Color(0xFF50C878)],
      explosionParticleCount: 130,
      explosionLife: 1.5,
      explosionGravity: 45.0,
      magnetStyle: MagnetStyle.lines,
      magnetColors: [Color(0xFF00A86B), Color(0xFFFFD700)],
      ambientStyle: AmbientStyle.fireflies,
      ambientColors: [Color(0xFF50C878), Color(0xFFFFD700)],
      ambientCount: 30,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFF00A86B),
      wallGlowIntensity: 0.35,
    ),

    // 29. Cosmic Rift
    VisualTheme(
      id: 't3_cosmic_rift',
      displayName: 'Cosmic Rift',
      tier: 3,
      variation: 8,
      ballShape: BallShape.slit,
      ballColors: [Color(0xFF00E5FF), Color(0xFFFF00FF)],
      ballGlowRadius: 14.0,
      ballGlowIntensity: 0.45,
      ballEffect: BallEffect.flicker,
      ballEffectSpeed: 2.0,
      trailStyle: TrailStyle.streaks,
      trailColors: [Color(0xFF00E5FF), Color(0xFFFF00FF), Color(0xFF7C4DFF)],
      trailWidth: 1.4,
      trailLife: 0.8,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.electric,
      obstacleColors: [Color(0xFF006978), Color(0xFF7B0080)],
      obstacleGlowIntensity: 0.45,
      explosionPattern: ExplosionPattern.implosion,
      explosionColors: [Color(0xFF00E5FF), Color(0xFFFF00FF), Color(0xFF7C4DFF), Color(0xFFFFFFFF)],
      explosionParticleCount: 150,
      explosionLife: 1.3,
      explosionGravity: 10.0,
      magnetStyle: MagnetStyle.electric,
      magnetColors: [Color(0xFF00E5FF), Color(0xFFFF00FF)],
      ambientStyle: AmbientStyle.stars,
      ambientColors: [Color(0xFF00E5FF), Color(0xFFFF00FF)],
      ambientCount: 35,
      wallStyle: WallStyle.electric,
      wallAccentColor: Color(0xFF7C4DFF),
      wallGlowIntensity: 0.40,
    ),

    // 30. Phoenix Rising
    VisualTheme(
      id: 't3_phoenix_rising',
      displayName: 'Phoenix Rising',
      tier: 3,
      variation: 9,
      ballShape: BallShape.star5,
      ballColors: [Color(0xFFFF6F00), Color(0xFFFFD54F)],
      ballGlowRadius: 15.0,
      ballGlowIntensity: 0.48,
      ballEffect: BallEffect.pulse,
      ballEffectSpeed: 1.0,
      trailStyle: TrailStyle.feathers,
      trailColors: [Color(0xFFFF6F00), Color(0xFFFFD54F), Color(0xFFFF3D00)],
      trailWidth: 1.5,
      trailLife: 1.3,
      trailDensity: 4,
      obstacleStyle: ObstacleStyle.flame,
      obstacleColors: [Color(0xFFE65100), Color(0xFFBF360C)],
      obstacleGlowIntensity: 0.45,
      explosionPattern: ExplosionPattern.fountain,
      explosionColors: [Color(0xFFFF6F00), Color(0xFFFFD54F), Color(0xFFFF3D00), Color(0xFFFFAB00)],
      explosionParticleCount: 190,
      explosionLife: 1.5,
      explosionGravity: 85.0,
      magnetStyle: MagnetStyle.arcs,
      magnetColors: [Color(0xFFFF6F00), Color(0xFFFFD54F)],
      ambientStyle: AmbientStyle.embers,
      ambientColors: [Color(0xFFFF6F00), Color(0xFFFFD54F), Color(0xFFFF3D00)],
      ambientCount: 40,
      wallStyle: WallStyle.flame,
      wallAccentColor: Color(0xFFFF6F00),
      wallGlowIntensity: 0.45,
    ),
  ];

  // ---------------------------------------------------------------------------
  // Tier 4 — "Legendary" (Score 400)
  // ---------------------------------------------------------------------------
  static const _tier4 = <VisualTheme>[
    // 31. Supernova
    VisualTheme(
      id: 't4_supernova',
      displayName: 'Supernova',
      tier: 4,
      variation: 0,
      ballShape: BallShape.circle,
      ballColors: [Color(0xFFFFFFFF), Color(0xFFFFF9C4)],
      ballGlowRadius: 20.0,
      ballGlowIntensity: 0.60,
      ballEffect: BallEffect.corona,
      ballEffectSpeed: 1.0,
      trailStyle: TrailStyle.flames,
      trailColors: [Color(0xFFFFF9C4), Color(0xFFFFEB3B), Color(0xFFFF6F00)],
      trailWidth: 2.0,
      trailLife: 1.0,
      trailDensity: 5,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFFE65100), Color(0xFFBF360C)],
      obstacleGlowIntensity: 0.50,
      explosionPattern: ExplosionPattern.nova,
      explosionColors: [Color(0xFFFFFFFF), Color(0xFFFFF9C4), Color(0xFFFFEB3B), Color(0xFFFF6F00)],
      explosionParticleCount: 250,
      explosionLife: 1.8,
      explosionGravity: 40.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFFFFF9C4), Color(0xFFFFEB3B)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFFFFF9C4), Color(0xFFFFEB3B), Color(0xFFFFFFFF)],
      ambientCount: 60,
      wallStyle: WallStyle.pulse,
      wallAccentColor: Color(0xFFFFEB3B),
      wallGlowIntensity: 0.50,
      invertedBallColors: [Color(0xFF3E2723), Color(0xFF4E342E)],
      invertedTrailColors: [Color(0xFF4E342E), Color(0xFF5D4037), Color(0xFFBF360C)],
      invertedObstacleColors: [Color(0xFFBF360C), Color(0xFF8D3A00)],
    ),

    // 32. Dark Matter
    VisualTheme(
      id: 't4_dark_matter',
      displayName: 'Dark Matter',
      tier: 4,
      variation: 1,
      ballShape: BallShape.singularity,
      ballColors: [Color(0xFF424242), Color(0xFF1A1A1A)],
      ballGlowRadius: 18.0,
      ballGlowIntensity: 0.30,
      ballEffect: BallEffect.ripple,
      ballEffectSpeed: 0.5,
      trailStyle: TrailStyle.waves,
      trailColors: [Color(0xFF424242), Color(0xFF212121), Color(0xFF616161)],
      trailWidth: 2.2,
      trailLife: 2.0,
      trailDensity: 2,
      obstacleStyle: ObstacleStyle.shadow,
      obstacleColors: [Color(0xFF0A0A0A), Color(0xFF050505)],
      obstacleGlowIntensity: 0.15,
      explosionPattern: ExplosionPattern.implosion,
      explosionColors: [Color(0xFF424242), Color(0xFF1A1A1A), Color(0xFF616161)],
      explosionParticleCount: 120,
      explosionLife: 2.2,
      explosionGravity: 5.0,
      magnetStyle: MagnetStyle.tendrils,
      magnetColors: [Color(0xFF424242)],
      ambientStyle: AmbientStyle.dust,
      ambientColors: [Color(0xFF424242), Color(0xFF212121)],
      ambientCount: 15,
      wallStyle: WallStyle.drip,
      wallAccentColor: Color(0xFF424242),
      wallGlowIntensity: 0.15,
    ),

    // 33. Crystal Prism
    VisualTheme(
      id: 't4_crystal_prism',
      displayName: 'Crystal Prism',
      tier: 4,
      variation: 2,
      ballShape: BallShape.prism,
      ballColors: [Color(0xFFFF1744), Color(0xFFFF9100), Color(0xFFFFEA00), Color(0xFF00E676), Color(0xFF2979FF), Color(0xFFD500F9)],
      ballGlowRadius: 16.0,
      ballGlowIntensity: 0.50,
      ballEffect: BallEffect.prismatic,
      ballEffectSpeed: 0.8,
      trailStyle: TrailStyle.sparkles,
      trailColors: [Color(0xFFFF1744), Color(0xFFFF9100), Color(0xFFFFEA00), Color(0xFF00E676), Color(0xFF2979FF), Color(0xFFD500F9)],
      trailWidth: 1.3,
      trailLife: 1.5,
      trailDensity: 5,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFF6200EA), Color(0xFF304FFE)],
      obstacleGlowIntensity: 0.45,
      explosionPattern: ExplosionPattern.ring,
      explosionColors: [Color(0xFFFF1744), Color(0xFFFF9100), Color(0xFFFFEA00), Color(0xFF00E676), Color(0xFF2979FF), Color(0xFFD500F9)],
      explosionParticleCount: 200,
      explosionLife: 1.6,
      explosionGravity: 30.0,
      magnetStyle: MagnetStyle.particles,
      magnetColors: [Color(0xFFFF1744), Color(0xFF00E676), Color(0xFF2979FF)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFFFF1744), Color(0xFFFFEA00), Color(0xFF00E676), Color(0xFF2979FF)],
      ambientCount: 50,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFFD500F9),
      wallGlowIntensity: 0.42,
    ),

    // 34. Berserker
    VisualTheme(
      id: 't4_berserker',
      displayName: 'Berserker',
      tier: 4,
      variation: 3,
      ballShape: BallShape.star6,
      ballColors: [Color(0xFFD50000), Color(0xFFFF1744)],
      ballGlowRadius: 14.0,
      ballGlowIntensity: 0.55,
      ballEffect: BallEffect.pulse,
      ballEffectSpeed: 2.0,
      trailStyle: TrailStyle.flames,
      trailColors: [Color(0xFFD50000), Color(0xFFFF1744), Color(0xFFFF6E40)],
      trailWidth: 2.0,
      trailLife: 0.7,
      trailDensity: 5,
      obstacleStyle: ObstacleStyle.flame,
      obstacleColors: [Color(0xFF8B0000), Color(0xFF4A0000)],
      obstacleGlowIntensity: 0.50,
      explosionPattern: ExplosionPattern.burst,
      explosionColors: [Color(0xFFD50000), Color(0xFFFF1744), Color(0xFFFF6E40), Color(0xFFFFAB00)],
      explosionParticleCount: 220,
      explosionLife: 1.0,
      explosionGravity: 130.0,
      magnetStyle: MagnetStyle.chains,
      magnetColors: [Color(0xFFD50000), Color(0xFFFF1744)],
      ambientStyle: AmbientStyle.embers,
      ambientColors: [Color(0xFFD50000), Color(0xFFFF6E40)],
      ambientCount: 35,
      wallStyle: WallStyle.flame,
      wallAccentColor: Color(0xFFD50000),
      wallGlowIntensity: 0.50,
    ),

    // 35. Time Warp
    VisualTheme(
      id: 't4_time_warp',
      displayName: 'Time Warp',
      tier: 4,
      variation: 4,
      ballShape: BallShape.gear,
      ballColors: [Color(0xFFFFD700), Color(0xFF1E88E5)],
      ballGlowRadius: 12.0,
      ballGlowIntensity: 0.38,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 0.3,
      trailStyle: TrailStyle.dots,
      trailColors: [Color(0xFFFFD700), Color(0xFF1E88E5), Color(0xFFB8860B)],
      trailWidth: 1.0,
      trailLife: 2.0,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.stripe,
      obstacleColors: [Color(0xFF0D47A1), Color(0xFF8D6E04)],
      obstacleGlowIntensity: 0.32,
      explosionPattern: ExplosionPattern.spiral,
      explosionColors: [Color(0xFFFFD700), Color(0xFF1E88E5), Color(0xFFB8860B), Color(0xFF64B5F6)],
      explosionParticleCount: 160,
      explosionLife: 2.0,
      explosionGravity: 20.0,
      magnetStyle: MagnetStyle.lines,
      magnetColors: [Color(0xFFFFD700), Color(0xFF1E88E5)],
      ambientStyle: AmbientStyle.dust,
      ambientColors: [Color(0xFFFFD700), Color(0xFF1E88E5)],
      ambientCount: 25,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFFFFD700),
      wallGlowIntensity: 0.32,
    ),

    // 36. Elemental Fury
    VisualTheme(
      id: 't4_elemental_fury',
      displayName: 'Elemental Fury',
      tier: 4,
      variation: 5,
      ballShape: BallShape.diamond,
      ballColors: [Color(0xFFFF1744), Color(0xFF00B0FF), Color(0xFF76FF03), Color(0xFFFFD600)],
      ballGlowRadius: 15.0,
      ballGlowIntensity: 0.48,
      ballEffect: BallEffect.morph,
      ballEffectSpeed: 1.2,
      trailStyle: TrailStyle.waves,
      trailColors: [Color(0xFFFF1744), Color(0xFF00B0FF), Color(0xFF76FF03), Color(0xFFFFD600)],
      trailWidth: 1.6,
      trailLife: 1.2,
      trailDensity: 4,
      obstacleStyle: ObstacleStyle.pulse,
      obstacleColors: [Color(0xFFB71C1C), Color(0xFF01579B)],
      obstacleGlowIntensity: 0.42,
      explosionPattern: ExplosionPattern.nova,
      explosionColors: [Color(0xFFFF1744), Color(0xFF00B0FF), Color(0xFF76FF03), Color(0xFFFFD600)],
      explosionParticleCount: 210,
      explosionLife: 1.5,
      explosionGravity: 55.0,
      magnetStyle: MagnetStyle.arcs,
      magnetColors: [Color(0xFFFF1744), Color(0xFF00B0FF)],
      ambientStyle: AmbientStyle.embers,
      ambientColors: [Color(0xFFFF1744), Color(0xFF76FF03), Color(0xFF00B0FF)],
      ambientCount: 40,
      wallStyle: WallStyle.pulse,
      wallAccentColor: Color(0xFFFFD600),
      wallGlowIntensity: 0.42,
    ),

    // 37. Celestial Dragon
    VisualTheme(
      id: 't4_celestial_dragon',
      displayName: 'Celestial Dragon',
      tier: 4,
      variation: 6,
      ballShape: BallShape.spiral,
      ballColors: [Color(0xFFFFD700), Color(0xFFFFA000)],
      ballGlowRadius: 17.0,
      ballGlowIntensity: 0.52,
      ballEffect: BallEffect.orbit,
      ballEffectSpeed: 0.7,
      trailStyle: TrailStyle.sparkles,
      trailColors: [Color(0xFFFFD700), Color(0xFFFFA000), Color(0xFFFFF176)],
      trailWidth: 1.4,
      trailLife: 1.6,
      trailDensity: 5,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFFB8860B), Color(0xFF7B5800)],
      obstacleGlowIntensity: 0.45,
      explosionPattern: ExplosionPattern.spiral,
      explosionColors: [Color(0xFFFFD700), Color(0xFFFFA000), Color(0xFFFFF176), Color(0xFFFFCC02)],
      explosionParticleCount: 180,
      explosionLife: 1.7,
      explosionGravity: 35.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFFFFD700), Color(0xFFFFA000)],
      ambientStyle: AmbientStyle.stars,
      ambientColors: [Color(0xFFFFD700), Color(0xFFFFF176)],
      ambientCount: 45,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFFFFD700),
      wallGlowIntensity: 0.45,
    ),

    // 38. Quantum Flux
    VisualTheme(
      id: 't4_quantum_flux',
      displayName: 'Quantum Flux',
      tier: 4,
      variation: 7,
      ballShape: BallShape.doubleRing,
      ballColors: [Color(0xFF448AFF), Color(0xFF82B1FF)],
      ballGlowRadius: 14.0,
      ballGlowIntensity: 0.42,
      ballEffect: BallEffect.phase,
      ballEffectSpeed: 1.5,
      trailStyle: TrailStyle.sparkles,
      trailColors: [Color(0xFF448AFF), Color(0xFF82B1FF), Color(0xFF2962FF)],
      trailWidth: 1.2,
      trailLife: 1.4,
      trailDensity: 4,
      obstacleStyle: ObstacleStyle.electric,
      obstacleColors: [Color(0xFF0D47A1), Color(0xFF1A237E)],
      obstacleGlowIntensity: 0.42,
      explosionPattern: ExplosionPattern.fractal,
      explosionColors: [Color(0xFF448AFF), Color(0xFF82B1FF), Color(0xFF2962FF), Color(0xFFE8EAF6)],
      explosionParticleCount: 190,
      explosionLife: 1.6,
      explosionGravity: 15.0,
      magnetStyle: MagnetStyle.pulses,
      magnetColors: [Color(0xFF448AFF), Color(0xFF82B1FF)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFF448AFF), Color(0xFF82B1FF)],
      ambientCount: 40,
      wallStyle: WallStyle.electric,
      wallAccentColor: Color(0xFF448AFF),
      wallGlowIntensity: 0.40,
    ),

    // 39. Abyssal Lord
    VisualTheme(
      id: 't4_abyssal_lord',
      displayName: 'Abyssal Lord',
      tier: 4,
      variation: 8,
      ballShape: BallShape.eye,
      ballColors: [Color(0xFF004D40), Color(0xFF00695C)],
      ballGlowRadius: 15.0,
      ballGlowIntensity: 0.38,
      ballEffect: BallEffect.breathe,
      ballEffectSpeed: 0.4,
      trailStyle: TrailStyle.bubbles,
      trailColors: [Color(0xFF004D40), Color(0xFF00695C), Color(0xFF26A69A)],
      trailWidth: 1.8,
      trailLife: 1.8,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.shadow,
      obstacleColors: [Color(0xFF002420), Color(0xFF001A16)],
      obstacleGlowIntensity: 0.22,
      explosionPattern: ExplosionPattern.cascade,
      explosionColors: [Color(0xFF004D40), Color(0xFF00695C), Color(0xFF26A69A), Color(0xFF80CBC4)],
      explosionParticleCount: 140,
      explosionLife: 2.0,
      explosionGravity: 10.0,
      magnetStyle: MagnetStyle.tendrils,
      magnetColors: [Color(0xFF004D40), Color(0xFF26A69A)],
      ambientStyle: AmbientStyle.bubbles,
      ambientColors: [Color(0xFF26A69A), Color(0xFF00695C)],
      ambientCount: 30,
      wallStyle: WallStyle.drip,
      wallAccentColor: Color(0xFF004D40),
      wallGlowIntensity: 0.22,
    ),

    // 40. Diamond Forge
    VisualTheme(
      id: 't4_diamond_forge',
      displayName: 'Diamond Forge',
      tier: 4,
      variation: 9,
      ballShape: BallShape.diamond,
      ballColors: [Color(0xFFFFFFFF), Color(0xFFE0F7FA), Color(0xFFF3E5F5)],
      ballGlowRadius: 18.0,
      ballGlowIntensity: 0.55,
      ballEffect: BallEffect.prismatic,
      ballEffectSpeed: 0.6,
      trailStyle: TrailStyle.crystals,
      trailColors: [Color(0xFFE0F7FA), Color(0xFFF3E5F5), Color(0xFFE8F5E9), Color(0xFFFFF3E0)],
      trailWidth: 1.3,
      trailLife: 1.6,
      trailDensity: 4,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFF00ACC1), Color(0xFF8E24AA)],
      obstacleGlowIntensity: 0.48,
      explosionPattern: ExplosionPattern.shatter,
      explosionColors: [Color(0xFFFFFFFF), Color(0xFFE0F7FA), Color(0xFFF3E5F5), Color(0xFFE8F5E9), Color(0xFFFFF3E0)],
      explosionParticleCount: 230,
      explosionLife: 1.8,
      explosionGravity: 25.0,
      magnetStyle: MagnetStyle.particles,
      magnetColors: [Color(0xFFE0F7FA), Color(0xFFF3E5F5)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFFE0F7FA), Color(0xFFF3E5F5), Color(0xFFE8F5E9)],
      ambientCount: 55,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFFE0F7FA),
      wallGlowIntensity: 0.48,
      invertedBallColors: [Color(0xFF37474F), Color(0xFF006064), Color(0xFF4A148C)],
      invertedTrailColors: [Color(0xFF006064), Color(0xFF4A148C), Color(0xFF1B5E20), Color(0xFFBF360C)],
      invertedObstacleColors: [Color(0xFF00838F), Color(0xFF6A1B9A)],
    ),
  ];

  // ---------------------------------------------------------------------------
  // Tier 5 — "Transcendence" (Score 500)
  // ---------------------------------------------------------------------------
  static const _tier5 = <VisualTheme>[
    // 41. Big Bang
    VisualTheme(
      id: 't5_big_bang',
      displayName: 'Big Bang',
      tier: 5,
      variation: 0,
      ballShape: BallShape.circle,
      ballColors: [Color(0xFFFFFFFF), Color(0xFFFF1744), Color(0xFF2979FF), Color(0xFFFFEA00), Color(0xFF00E676)],
      ballGlowRadius: 22.0,
      ballGlowIntensity: 0.65,
      ballEffect: BallEffect.corona,
      ballEffectSpeed: 0.8,
      trailStyle: TrailStyle.sparkles,
      trailColors: [Color(0xFFFFFFFF), Color(0xFFFF1744), Color(0xFF2979FF), Color(0xFFFFEA00), Color(0xFF00E676)],
      trailWidth: 1.5,
      trailLife: 1.4,
      trailDensity: 6,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFFB71C1C), Color(0xFF0D47A1)],
      obstacleGlowIntensity: 0.55,
      explosionPattern: ExplosionPattern.nova,
      explosionColors: [Color(0xFFFFFFFF), Color(0xFFFF1744), Color(0xFF2979FF), Color(0xFFFFEA00), Color(0xFF00E676), Color(0xFFD500F9)],
      explosionParticleCount: 300,
      explosionLife: 2.0,
      explosionGravity: 35.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFFFF1744), Color(0xFF2979FF), Color(0xFFFFEA00)],
      ambientStyle: AmbientStyle.stars,
      ambientColors: [Color(0xFFFFFFFF), Color(0xFFFF1744), Color(0xFF2979FF), Color(0xFFFFEA00)],
      ambientCount: 70,
      wallStyle: WallStyle.pulse,
      wallAccentColor: Color(0xFFFFFFFF),
      wallGlowIntensity: 0.55,
      invertedBallColors: [Color(0xFF212121), Color(0xFFB71C1C), Color(0xFF0D47A1), Color(0xFFF57F17), Color(0xFF1B5E20)],
      invertedTrailColors: [Color(0xFF212121), Color(0xFFB71C1C), Color(0xFF0D47A1), Color(0xFFF57F17), Color(0xFF1B5E20)],
      invertedObstacleColors: [Color(0xFF880E0E), Color(0xFF0A3380)],
    ),

    // 42. Event Horizon
    VisualTheme(
      id: 't5_event_horizon',
      displayName: 'Event Horizon',
      tier: 5,
      variation: 1,
      ballShape: BallShape.singularity,
      ballColors: [Color(0xFF0A0A0A), Color(0xFFFFD700)],
      ballGlowRadius: 20.0,
      ballGlowIntensity: 0.45,
      ballEffect: BallEffect.orbit,
      ballEffectSpeed: 0.4,
      trailStyle: TrailStyle.waves,
      trailColors: [Color(0xFFFFD700), Color(0xFF0A0A0A), Color(0xFFB8860B)],
      trailWidth: 2.4,
      trailLife: 2.2,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.shadow,
      obstacleColors: [Color(0xFF050505), Color(0xFF0A0A0A)],
      obstacleGlowIntensity: 0.18,
      explosionPattern: ExplosionPattern.vortex,
      explosionColors: [Color(0xFFFFD700), Color(0xFF0A0A0A), Color(0xFFB8860B), Color(0xFFFFFFFF)],
      explosionParticleCount: 200,
      explosionLife: 2.5,
      explosionGravity: 0.0,
      magnetStyle: MagnetStyle.tendrils,
      magnetColors: [Color(0xFFFFD700), Color(0xFF0A0A0A)],
      ambientStyle: AmbientStyle.dust,
      ambientColors: [Color(0xFFFFD700), Color(0xFF0A0A0A)],
      ambientCount: 20,
      wallStyle: WallStyle.crack,
      wallAccentColor: Color(0xFFFFD700),
      wallGlowIntensity: 0.25,
    ),

    // 43. Neural Network
    VisualTheme(
      id: 't5_neural_network',
      displayName: 'Neural Network',
      tier: 5,
      variation: 2,
      ballShape: BallShape.cross,
      ballColors: [Color(0xFFFF4081), Color(0xFF448AFF)],
      ballGlowRadius: 16.0,
      ballGlowIntensity: 0.48,
      ballEffect: BallEffect.orbit,
      ballEffectSpeed: 1.2,
      trailStyle: TrailStyle.lightning,
      trailColors: [Color(0xFFFF4081), Color(0xFF448AFF), Color(0xFF7C4DFF)],
      trailWidth: 1.2,
      trailLife: 1.0,
      trailDensity: 5,
      obstacleStyle: ObstacleStyle.electric,
      obstacleColors: [Color(0xFF880E4F), Color(0xFF1A237E)],
      obstacleGlowIntensity: 0.45,
      explosionPattern: ExplosionPattern.fractal,
      explosionColors: [Color(0xFFFF4081), Color(0xFF448AFF), Color(0xFF7C4DFF), Color(0xFF18FFFF)],
      explosionParticleCount: 240,
      explosionLife: 1.5,
      explosionGravity: 20.0,
      magnetStyle: MagnetStyle.electric,
      magnetColors: [Color(0xFFFF4081), Color(0xFF448AFF)],
      ambientStyle: AmbientStyle.fireflies,
      ambientColors: [Color(0xFFFF4081), Color(0xFF448AFF), Color(0xFF7C4DFF)],
      ambientCount: 55,
      wallStyle: WallStyle.electric,
      wallAccentColor: Color(0xFF7C4DFF),
      wallGlowIntensity: 0.45,
    ),

    // 44. DNA Helix
    VisualTheme(
      id: 't5_dna_helix',
      displayName: 'DNA Helix',
      tier: 5,
      variation: 3,
      ballShape: BallShape.helix,
      ballColors: [Color(0xFF00E676), Color(0xFF2979FF)],
      ballGlowRadius: 14.0,
      ballGlowIntensity: 0.42,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 0.6,
      trailStyle: TrailStyle.ribbons,
      trailColors: [Color(0xFF00E676), Color(0xFF2979FF), Color(0xFF69F0AE), Color(0xFF82B1FF)],
      trailWidth: 1.4,
      trailLife: 1.6,
      trailDensity: 4,
      obstacleStyle: ObstacleStyle.pulse,
      obstacleColors: [Color(0xFF00695C), Color(0xFF0D47A1)],
      obstacleGlowIntensity: 0.38,
      explosionPattern: ExplosionPattern.bloom,
      explosionColors: [Color(0xFF00E676), Color(0xFF2979FF), Color(0xFF69F0AE), Color(0xFF82B1FF)],
      explosionParticleCount: 180,
      explosionLife: 1.7,
      explosionGravity: 25.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFF00E676), Color(0xFF2979FF)],
      ambientStyle: AmbientStyle.bubbles,
      ambientColors: [Color(0xFF69F0AE), Color(0xFF82B1FF)],
      ambientCount: 40,
      wallStyle: WallStyle.pulse,
      wallAccentColor: Color(0xFF00E676),
      wallGlowIntensity: 0.38,
    ),

    // 45. Pure Singularity
    VisualTheme(
      id: 't5_pure_singularity',
      displayName: 'Pure Singularity',
      tier: 5,
      variation: 4,
      ballShape: BallShape.singularity,
      ballColors: [Color(0xFFFFFFFF), Color(0xFFFFD700)],
      ballGlowRadius: 24.0,
      ballGlowIntensity: 0.70,
      ballEffect: BallEffect.ripple,
      ballEffectSpeed: 0.5,
      trailStyle: TrailStyle.streaks,
      trailColors: [Color(0xFFFFFFFF), Color(0xFFFFD700), Color(0xFFFFF9C4)],
      trailWidth: 1.8,
      trailLife: 1.2,
      trailDensity: 3,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFFB8860B), Color(0xFF7B5800)],
      obstacleGlowIntensity: 0.52,
      explosionPattern: ExplosionPattern.implosion,
      explosionColors: [Color(0xFFFFFFFF), Color(0xFFFFD700), Color(0xFFFFF9C4), Color(0xFFFFC107)],
      explosionParticleCount: 200,
      explosionLife: 2.0,
      explosionGravity: 0.0,
      magnetStyle: MagnetStyle.pulses,
      magnetColors: [Color(0xFFFFFFFF), Color(0xFFFFD700)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFFFFFFFF), Color(0xFFFFD700), Color(0xFFFFF9C4)],
      ambientCount: 60,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFFFFD700),
      wallGlowIntensity: 0.52,
      invertedBallColors: [Color(0xFF212121), Color(0xFF5D4037)],
      invertedTrailColors: [Color(0xFF212121), Color(0xFF5D4037), Color(0xFF4E342E)],
      invertedObstacleColors: [Color(0xFF8D6E04), Color(0xFF5D4037)],
    ),

    // 46. Antimatter
    VisualTheme(
      id: 't5_antimatter',
      displayName: 'Antimatter',
      tier: 5,
      variation: 5,
      ballShape: BallShape.circle,
      ballColors: [Color(0xFF7C4DFF), Color(0xFF18FFFF)],
      ballGlowRadius: 16.0,
      ballGlowIntensity: 0.50,
      ballEffect: BallEffect.phase,
      ballEffectSpeed: 1.8,
      trailStyle: TrailStyle.shadows,
      trailColors: [Color(0xFF7C4DFF), Color(0xFF18FFFF), Color(0xFF1A1A2E)],
      trailWidth: 1.6,
      trailLife: 1.3,
      trailDensity: 4,
      obstacleStyle: ObstacleStyle.shadow,
      obstacleColors: [Color(0xFF1A1A2E), Color(0xFF0D0D1A)],
      obstacleGlowIntensity: 0.35,
      explosionPattern: ExplosionPattern.nova,
      explosionColors: [Color(0xFF7C4DFF), Color(0xFF18FFFF), Color(0xFFFF4081), Color(0xFFFFFFFF)],
      explosionParticleCount: 220,
      explosionLife: 1.4,
      explosionGravity: 45.0,
      magnetStyle: MagnetStyle.electric,
      magnetColors: [Color(0xFF7C4DFF), Color(0xFF18FFFF)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFF7C4DFF), Color(0xFF18FFFF)],
      ambientCount: 45,
      wallStyle: WallStyle.crack,
      wallAccentColor: Color(0xFF7C4DFF),
      wallGlowIntensity: 0.40,
    ),

    // 47. Fourth Dimension
    VisualTheme(
      id: 't5_fourth_dimension',
      displayName: 'Fourth Dimension',
      tier: 5,
      variation: 6,
      ballShape: BallShape.tesseract,
      ballColors: [Color(0xFF536DFE), Color(0xFFB388FF)],
      ballGlowRadius: 18.0,
      ballGlowIntensity: 0.48,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 0.5,
      trailStyle: TrailStyle.waves,
      trailColors: [Color(0xFF536DFE), Color(0xFFB388FF), Color(0xFF8C9EFF)],
      trailWidth: 1.6,
      trailLife: 1.8,
      trailDensity: 4,
      obstacleStyle: ObstacleStyle.electric,
      obstacleColors: [Color(0xFF1A237E), Color(0xFF311B92)],
      obstacleGlowIntensity: 0.45,
      explosionPattern: ExplosionPattern.fractal,
      explosionColors: [Color(0xFF536DFE), Color(0xFFB388FF), Color(0xFF8C9EFF), Color(0xFFE8EAF6)],
      explosionParticleCount: 250,
      explosionLife: 2.0,
      explosionGravity: 10.0,
      magnetStyle: MagnetStyle.pulses,
      magnetColors: [Color(0xFF536DFE), Color(0xFFB388FF)],
      ambientStyle: AmbientStyle.stars,
      ambientColors: [Color(0xFF536DFE), Color(0xFFB388FF), Color(0xFF8C9EFF)],
      ambientCount: 55,
      wallStyle: WallStyle.electric,
      wallAccentColor: Color(0xFF536DFE),
      wallGlowIntensity: 0.45,
    ),

    // 48. God Particle
    VisualTheme(
      id: 't5_god_particle',
      displayName: 'God Particle',
      tier: 5,
      variation: 7,
      ballShape: BallShape.circle,
      ballColors: [Color(0xFFFFD700), Color(0xFF1565C0)],
      ballGlowRadius: 20.0,
      ballGlowIntensity: 0.55,
      ballEffect: BallEffect.ripple,
      ballEffectSpeed: 0.7,
      trailStyle: TrailStyle.sparkles,
      trailColors: [Color(0xFFFFD700), Color(0xFF1565C0), Color(0xFFFFF176), Color(0xFF64B5F6)],
      trailWidth: 1.3,
      trailLife: 1.5,
      trailDensity: 5,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFF0D47A1), Color(0xFF8D6E04)],
      obstacleGlowIntensity: 0.48,
      explosionPattern: ExplosionPattern.bloom,
      explosionColors: [Color(0xFFFFD700), Color(0xFF1565C0), Color(0xFFFFF176), Color(0xFF64B5F6), Color(0xFFFFFFFF)],
      explosionParticleCount: 220,
      explosionLife: 1.8,
      explosionGravity: 30.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFFFFD700), Color(0xFF1565C0)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFFFFD700), Color(0xFF1565C0), Color(0xFFFFF176)],
      ambientCount: 50,
      wallStyle: WallStyle.pulse,
      wallAccentColor: Color(0xFFFFD700),
      wallGlowIntensity: 0.48,
    ),

    // 49. Omega Point
    VisualTheme(
      id: 't5_omega_point',
      displayName: 'Omega Point',
      tier: 5,
      variation: 8,
      ballShape: BallShape.circle,
      ballColors: [Color(0xFFFFFFFF), Color(0xFFFF1744), Color(0xFFFFEA00), Color(0xFF00E676), Color(0xFF2979FF), Color(0xFFAA00FF)],
      ballGlowRadius: 22.0,
      ballGlowIntensity: 0.62,
      ballEffect: BallEffect.breathe,
      ballEffectSpeed: 0.5,
      trailStyle: TrailStyle.ribbons,
      trailColors: [Color(0xFFFF1744), Color(0xFFFFEA00), Color(0xFF00E676), Color(0xFF2979FF), Color(0xFFAA00FF)],
      trailWidth: 1.6,
      trailLife: 1.8,
      trailDensity: 5,
      obstacleStyle: ObstacleStyle.glow,
      obstacleColors: [Color(0xFFB71C1C), Color(0xFF1A237E)],
      obstacleGlowIntensity: 0.50,
      explosionPattern: ExplosionPattern.spiral,
      explosionColors: [Color(0xFFFFFFFF), Color(0xFFFF1744), Color(0xFFFFEA00), Color(0xFF00E676), Color(0xFF2979FF), Color(0xFFAA00FF)],
      explosionParticleCount: 280,
      explosionLife: 2.2,
      explosionGravity: 20.0,
      magnetStyle: MagnetStyle.waves,
      magnetColors: [Color(0xFFFF1744), Color(0xFF2979FF), Color(0xFF00E676)],
      ambientStyle: AmbientStyle.stars,
      ambientColors: [Color(0xFFFFFFFF), Color(0xFFFF1744), Color(0xFFFFEA00), Color(0xFF00E676)],
      ambientCount: 65,
      wallStyle: WallStyle.glow,
      wallAccentColor: Color(0xFFFFFFFF),
      wallGlowIntensity: 0.52,
      invertedBallColors: [Color(0xFF212121), Color(0xFFB71C1C), Color(0xFFF57F17), Color(0xFF1B5E20), Color(0xFF0D47A1), Color(0xFF6A00A8)],
      invertedTrailColors: [Color(0xFFB71C1C), Color(0xFFF57F17), Color(0xFF1B5E20), Color(0xFF0D47A1), Color(0xFF6A00A8)],
      invertedObstacleColors: [Color(0xFF880E0E), Color(0xFF0A3380)],
    ),

    // 50. The Architect
    VisualTheme(
      id: 't5_the_architect',
      displayName: 'The Architect',
      tier: 5,
      variation: 9,
      ballShape: BallShape.cube,
      ballColors: [Color(0xFF42A5F5), Color(0xFFE3F2FD)],
      ballGlowRadius: 15.0,
      ballGlowIntensity: 0.45,
      ballEffect: BallEffect.spin,
      ballEffectSpeed: 0.4,
      trailStyle: TrailStyle.code,
      trailColors: [Color(0xFF42A5F5), Color(0xFFE3F2FD), Color(0xFF1565C0)],
      trailWidth: 1.2,
      trailLife: 1.6,
      trailDensity: 5,
      obstacleStyle: ObstacleStyle.stripe,
      obstacleColors: [Color(0xFF0D47A1), Color(0xFF1A237E)],
      obstacleGlowIntensity: 0.38,
      explosionPattern: ExplosionPattern.fractal,
      explosionColors: [Color(0xFF42A5F5), Color(0xFFE3F2FD), Color(0xFF1565C0), Color(0xFFBBDEFB)],
      explosionParticleCount: 200,
      explosionLife: 1.8,
      explosionGravity: 15.0,
      magnetStyle: MagnetStyle.lines,
      magnetColors: [Color(0xFF42A5F5), Color(0xFFE3F2FD)],
      ambientStyle: AmbientStyle.sparkle,
      ambientColors: [Color(0xFF42A5F5), Color(0xFFE3F2FD)],
      ambientCount: 40,
      wallStyle: WallStyle.electric,
      wallAccentColor: Color(0xFF42A5F5),
      wallGlowIntensity: 0.40,
      invertedBallColors: [Color(0xFF0D47A1), Color(0xFF1A237E)],
      invertedTrailColors: [Color(0xFF0D47A1), Color(0xFF1A237E), Color(0xFF0A3380)],
      invertedObstacleColors: [Color(0xFF0A3380), Color(0xFF0D1B5E)],
    ),
  ];
}
